-- Poenta Supabase starter schema
-- Run this once in Supabase SQL Editor.
-- Uses public publishable/anon inserts only; no secret key is needed in the browser.

create table if not exists public.poenta_usage_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  device_id text,
  event_type text not null,
  path text,
  client_ts timestamptz,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.poenta_feedback_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  device_id text,
  card_key text,
  source_url text,
  source text,
  category text,
  headline text,
  feedback text,
  client_ts timestamptz,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.poenta_saved_item_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  device_id text,
  card_key text,
  action text not null,
  source text,
  category text,
  headline text,
  source_url text,
  client_ts timestamptz,
  item jsonb not null default '{}'::jsonb
);

create table if not exists public.poenta_preference_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  device_id text,
  changed_area text,
  path text,
  client_ts timestamptz,
  preferences jsonb not null default '{}'::jsonb
);

alter table public.poenta_usage_events enable row level security;
alter table public.poenta_feedback_events enable row level security;
alter table public.poenta_saved_item_events enable row level security;
alter table public.poenta_preference_events enable row level security;

create policy "poenta anon insert usage" on public.poenta_usage_events
  for insert to anon with check (true);
create policy "poenta anon insert feedback" on public.poenta_feedback_events
  for insert to anon with check (true);
create policy "poenta anon insert saved item events" on public.poenta_saved_item_events
  for insert to anon with check (true);
create policy "poenta anon insert preference events" on public.poenta_preference_events
  for insert to anon with check (true);

-- Optional read access for authenticated admins can be added later.
-- Keep service_role/secret keys out of frontend code.
