#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Regression drill for semantic duplicate story filtering.

This drill covers cases where two cards are the same news event from different
sources but wording overlap is too low for exact/title-only dedupe.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from pointa_live_auditor import likely_duplicate_story  # noqa: E402
import update_feed  # noqa: E402


CASES = [
    (
        "israel_strike_lebanese_army_soldiers_nabatieh_visible_regression_20260606",
        True,
        {
            "source": "וואלה חדשות - מבזקים",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "תקיפה ישראלית בדרום לבנון הרגה חיילים בצבא לבנון",
            "originalTitle": "דיווח: מספר חיילים לבנונים נהרגו בתקיפה ישראלית על רכב צבאי",
            "context": "צבא לבנון הודיע שמספר חיילים, בהם קצין, נהרגו בתקיפה ישראלית על רכב צבאי בכביש חרדלי־נבטיה. פגיעה בצבא הרשמי של לבנון מעלה את רמת הרגישות סביב הלחימה בדרום המדינה.",
            "sourceUrl": "https://news.walla.co.il/break/3843514",
        },
        {
            "source": "ynet - מבזקי החדשות",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "צבא לבנון הודיע שחיילים וקצין נהרגו בתקיפה ליד נבטיה",
            "originalTitle": "צבא לבנון: חיילים וקצין נהרגו בתקיפה הישראלית בנבטיה",
            "context": "צבא לבנון הודיע שחיילים וקצין נהרגו בתקיפה ישראלית באזור נבטיה. האירוע מעלה את הסיכון שהלחימה בדרום לבנון תסבך גם את הצבא הרשמי ולא רק את חיזבאללה.",
            "sourceUrl": "https://www.ynet.co.il/news/article/hylizbwbmx",
        },
    ),
    (
        "trump_iran_remaining_missile_drone_capability_visible_regression_20260606",
        True,
        {
            "source": "וואלה חדשות - מבזקים",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "טראמפ טוען שלאיראן נותר רק כחמישית מכוח הטילים והכטב״מים",
            "originalTitle": "טראמפ: לאיראן נותרו רק כ-21%-22% מיכולות הטילים והכטב\"מים שלה",
            "context": "טראמפ אמר שלאיראן נותרו כ־21%–22% מיכולות הטילים והכטב״מים שלה. ההצהרה נועדה להציג את הלחץ הצבאי והמדיני כמי שכבר שחק משמעותית את יכולת התגובה של טהרן.",
            "sourceUrl": "https://news.walla.co.il/break/3843484",
        },
        {
            "source": "ynet - מבזקי החדשות",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "טראמפ טוען שלאיראן נותרו רק כחמישית מהטילים",
            "originalTitle": "טראמפ: לאיראן נותרו רק כ-21%-22% מהטילים והכטב\"מים שהיו ברשותה",
            "context": "טראמפ אמר כי לאיראן נותרו כ-21% עד 22% מהטילים והכטב״מים שהיו לה לפני המלחמה. הטענה סותרת הערכות קודמות שלפיהן איראן שמרה על חלק גדול בהרבה ממלאי הטילים והכטב״מים.",
            "sourceUrl": "https://www.ynet.co.il/news/article/hkw3q6ewge",
        },
    ),
    (
        "trump_iran_deal_or_hard_way_visible_regression_20260606",
        True,
        {
            "source": "Israel National News English",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "טראמפ אמר שהמלחמה מול איראן תיגמר כך או אחרת",
            "originalTitle": "Trump on Iran war: One way or the other, it's finished",
            "context": "טראמפ אמר לחקלאים בוויסקונסין שארה״ב הצליחה למנוע את תוכנית הגרעין של איראן. לדבריו, הסיום יכול להגיע בהסכם כתוב או בדרך קשה יותר.",
            "sourceUrl": "https://www.israelnationalnews.com/flashes/687075",
        },
        {
            "source": "ynet - מבזקי החדשות",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "טראמפ הזהיר שאיראן תבחר בין הסכם לדרך קשה יותר",
            "originalTitle": "טראמפ על איראן: זה יסתיים בהסכם כתוב או בדרך הקשה",
            "context": "טראמפ אמר שהעימות סביב תוכנית הגרעין האיראנית יסתיים או בחתימה על הסכם או בדרך קשה יותר. האמירה מגיעה בזמן שהממשל מנסה לשמור את המגעים עם איראן פתוחים.",
            "sourceUrl": "https://www.ynet.co.il/news/article/rjfb52lwfl",
        },
    ),
    (
        "iran_hormuz_drones_intercepted_visible_regression_20260606",
        True,
        {
            "source": "The Guardian Middle East",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "ארה״ב תקפה מכ״מים איראניים אחרי שכטב״מים שוגרו להורמוז",
            "originalTitle": "US says Iran radar sites struck and drones intercepted, in latest threat to fragile ceasefire",
            "context": "צבא ארה״ב יירט ארבעה כטב״מים איראניים ששוגרו לעבר מצר הורמוז ותקף אתרי מכ״ם חופיים באיראן. ההסלמה מאיימת על הפסקת האש ועל נתיב האנרגיה המרכזי במפרץ.",
            "sourceUrl": "https://www.theguardian.com/world/2026/jun/06/us-says-iran-radar-sites-struck-and-drones-intercepted-in-latest-threat-to-fragile-ceasefire",
        },
        {
            "source": "ynet - מבזקי החדשות",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "ארה״ב אומרת שאיראן שיגרה כטב״מים רבים להורמוז",
            "originalTitle": "גורם אמריקני: איראן שיגרה כטב\"מים רבים לעבר מצר הורמוז, 4 יורטו",
            "context": "גורם אמריקני אמר שאיראן שיגרה מספר רב של כטב״מים לעבר מצר הורמוז, וארבעה מהם יורטו. התקרית מדגישה את הסיכון הישיר לנתיב האנרגיה המרכזי בזמן ההסלמה מול טהראן.",
            "sourceUrl": "https://www.ynet.co.il/news/article/b1na96ewze",
        },
    ),
    (
        "iran_hormuz_kuwait_bahrain_radar_strike_visible_regression_20260606",
        True,
        {
            "source": "וואלה חדשות - חדשות בעולם",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "ארה״ב תקפה מכ״מים באיראן אחרי שיגור כטב״מים להורמוז",
            "originalTitle": "עדיין בדרך להסכם? ארה\"ב תקפה אתרי מכ\"ם, איראן שיגרה טילים בליסטיים",
            "context": "פיקוד המרכז האמריקאי יירט ארבעה כטב״מים איראניים ששוגרו לעבר מצר הורמוז, ואז תקף אתרי מכ״ם איראניים בגורוק ובאי קשם. איראן הגיבה בירי טילים בליסטיים לעבר בסיסים אמריקאיים בכוויית ובבחריין, שרובם יורטו.",
            "sourceUrl": "https://news.walla.co.il/item/3843501",
        },
        {
            "source": "ישראל היום - כל הכתבות",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "ארה״ב תקפה מכ״מים באיראן אחרי ירי לעבר כוויית ובחריין",
            "originalTitle": "חילופי מהלומות במפרץ: ארה\"ב תקפה באיראן, טילים שוגרו לכווית ובחריין",
            "context": "העימות במפרץ הסלים לאחר שאיראן שיגרה כטב״מים לעבר מצר הורמוז וטילים לעבר כוויית ובחריין, וארה״ב תקפה בתגובה אתרי מכ״ם ומעקב באיראן. סנטקום טען שרוב האיומים יורטו ושהתקיפות נועדו למנוע פגיעה נוספת בנתיבי השיט.",
            "sourceUrl": "https://www.israelhayom.co.il/news/world-news/middle-east/article/20698866",
        },
    ),
    (
        "hebron_idf_civilian_baby_shooting_visible_regression_20260606",
        True,
        {
            "source": "וואלה חדשות - מבזקים",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "תינוק פלסטיני נהרג מירי צה״ל בחברון; האירוע נבדק",
            "originalTitle": "דיווח פלסטיני: תינוק נהרג מאש צה\"ל בחברון, הוריו נפצעו; בצבא הגיבו: הכוח חש שרכבם האיץ לעברם",
            "context": "משרד הבריאות הפלסטיני הודיע שתינוק בן שבעה חודשים נהרג מירי כוחות צה״ל בחברון ושני הוריו נפצעו. צה״ל מסר שכוח ירה לעבר רכב שהאיץ לכיוונו, שהתחקור הראשוני מצביע על פגיעה בבלתי מעורבים ושהאירוע נבדק.",
            "sourceUrl": "https://news.walla.co.il/item/3843483",
        },
        {
            "source": "The Jerusalem Post - Israel News",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "צה״ל פצע שלושה פלסטינים בחברון לאחר זיהוי שגוי",
            "originalTitle": "IDF mistakenly shoots three Palestinian civilians in Hebron",
            "context": "כוח צה״ל ירה לעבר רכב בחברון לאחר שסבר שהוא מאיץ לעברו, ושלושה פלסטינים בלתי מעורבים נפצעו. הצבא פתח בבדיקת האירוע והביע צער על הפגיעה באזרחים.",
            "sourceUrl": "https://www.jpost.com/israel-news/article-898508",
        },
    ),
    (
        "north_aircraft_fire_alert_ynet_walla_visible_regression_20260606",
        True,
        {
            "source": "ynet - כל ערוץ החדשות",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "חיזבאללה ירה לעבר כלי טיס וישראל העבירה אזהרה ללבנון",
            "originalTitle": "חיזבאללה ירה על כלי טיס; דיווח: המסר שעבר ללבנון - פגיעה בישראל תגרור אש בדאחייה",
            "context": "חיזבאללה ירה לעבר כלי טיס של חיל האוויר והירי הוביל לאזעקות בצפון, בלי פגיעה בכלי הטיס ובלי נפגעים. במקביל הועבר ללבנון מסר שלפיו פגיעה בישראל תגרור תגובה גם בדאחייה בביירות.",
            "sourceUrl": "https://www.ynet.co.il/news/article/r1wdrsgwfl",
        },
        {
            "source": "וואלה חדשות - צבא וביטחון",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "אזעקות בצפון הופעלו אחרי ירי לעבר מטוס חיל האוויר",
            "originalTitle": "לאחר יום מתוח בצפון: אזעקות מירי לעבר כלי טיס של חיה\"א",
            "context": "ירי לעבר כלי טיס של חיל האוויר הוביל להפעלת אזעקות בצפון אחרי יום מתוח בגבול לבנון. לפי הדיווחים, לא נרשמה פגיעה בכלי הטיס ולא היו נפגעים.",
            "sourceUrl": "https://news.walla.co.il/item/3843477",
        },
    ),
    (
        "khamenei_us_iran_nuclear_talks_deadlock_visible_regression_20260605",
        True,
        {
            "source": "הארץ - המזרח התיכון",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "יועץ חמינאי מציב שחרור 24 מיליארד דולר כתנאי להסכם",
            "originalTitle": "יועצו של חמינאי: המו\"מ עם ארה\"ב במבוי סתום, הסכם תלוי בשחרור נכסינו המוקפאים",
            "context": "יועץ חמינאי אמר שהמשא ומתן עם ארה״ב במבוי סתום ותלה הסכם בשחרור נכסים מוקפאים.",
            "sourceUrl": "https://www.haaretz.co.il/news/world/middle-east/2026-06-05/ty-article/.premium/0000019e-98e5-d59e-a79f-fae7ade70000",
        },
        {
            "source": "The Jerusalem Post - Iran News",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "יועץ חמינאי טוען שטראמפ תוקע את שיחות הגרעין",
            "originalTitle": "'At a deadlock': Khamenei's military advisor tells CNN that Trump is stalling talks",
            "context": "יועץ חמינאי טען שהשיחות עם ארה״ב תקועות משום שטראמפ מעכב את המשא ומתן.",
            "sourceUrl": "https://www.jpost.com/middle-east/iran-news/article-898504",
        },
    ),
    (
        "khamenei_us_iran_regional_war_threat_jpost_inn_visible_regression_20260605",
        True,
        {
            "source": "The Jerusalem Post - Middle East",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "יועץ חמינאי מציב לטראמפ תנאי כספי לחידוש שיחות הגרעין",
            "originalTitle": "'At a deadlock': Khamenei's military advisor tells CNN that Trump is stalling talks",
            "context": "מוחסן רזאי אמר שהמו״מ בין ארה״ב לאיראן תקוע ותלה את הפריצה בשחרור 24 מיליארד דולר מנכסים מוקפאים. הוא הזהיר שאם הלחימה תתחדש, איראן תרחיב את הפגיעה בבסיסים אמריקאיים.",
            "sourceUrl": "https://www.jpost.com/middle-east/iran-news/article-898504",
        },
        {
            "source": "ערוץ 7 / INN עברית",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "יועץ חמינאי איים להרחיב את המלחמה לכל האזור",
            "originalTitle": "יועצו של חמינאי: אם הלחימה תימשך נרחיב את העימות לאזור כולו",
            "context": "יועצו של חמינאי הזהיר שאם הלחימה תימשך איראן ובעלות בריתה ירחיבו את העימות לאזור כולו מול ישראל או ארה״ב.",
            "sourceUrl": "https://www.inn.co.il/flashes/1116443",
        },
    ),
    (
        "haredi_police_station_jerusalem_arrests_protest_visible_regression_20260605",
        True,
        {
            "source": "The Jerusalem Post - Israel News",
            "category": "פלילים",
            "categoryClass": "security",
            "headline": "מפגינים חרדים תקפו עובר אורח ליד תחנת משטרה בירושלים",
            "originalTitle": "Man attacked by haredi protesters outside Jerusalem police station - report",
            "context": "מפגינים חרדים תקפו עובר אורח ליד תחנת משטרה בירושלים לאחר מעצר מתפרעים.",
            "sourceUrl": "https://www.jpost.com/israel-news/article-898506",
        },
        {
            "source": "ynet - מבזקי החדשות",
            "category": "פלילים",
            "categoryClass": "security",
            "headline": "חרדים הפגינו בתחנת משטרה בירושלים אחרי מעצר מתפרעים",
            "originalTitle": "עשרות חרדים מפגינים בתחנת המשטרה בי-ם, במחאה על מעצר המתפרעים מול בית סולברג",
            "context": "עשרות חרדים הפגינו בתחנת המשטרה בירושלים במחאה על מעצר המתפרעים מול בית סולברג.",
            "sourceUrl": "https://www.ynet.co.il/news/article/bjvw6ye11fg",
        },
    ),
    (
        "binyamin_firebomb_terrorist_inn_idf_visible_regression_20260605",
        True,
        {
            "source": "Israel National News English",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "מחבל שהשליך בקבוקי תבערה חוסל בין גבעת אסף לעפרה",
            "originalTitle": "Firebomb-throwing terrorist eliminated between Givat Assaf and Ofra",
            "context": "כוח ביטחון חיסל מחבל שהשליך בקבוקי תבערה באזור שבין גבעת אסף לעפרה.",
            "sourceUrl": "https://www.israelnationalnews.com/flashes/687009",
        },
        {
            "source": "דובר צה״ל - טלגרם רשמי",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "כוחות יחידה 636 חיסלו מחבל שיידה בקבוקי תבערה לעבר כביש מרכזי סמוך לכפר",
            "originalTitle": "דובר צה״ל:",
            "context": "כוחות יחידה 636 במרחב הכפר ביתין שבחטיבת בנימין זיהו מחבלים שזרקו בקבוקי תבערה לעבר רכבים ישראלים וחיסלו אחד מהם.",
            "sourceUrl": "https://t.me/idf_telegram/24153",
        },
    ),
    (
        "tamra_yafia_triple_murder_ynet_israelhayom_visible_regression_20260605",
        True,
        {
            "source": "ynet - כל ערוץ החדשות",
            "category": "פלילים",
            "categoryClass": "security",
            "headline": "שלושה גברים נרצחו ביריות בתוך שעות באזור נצרת ובטמרה",
            "originalTitle": "שני צעירים נרצחו ביריות ליד נצרת, גבר נורה למוות בטמרה",
            "context": "שני צעירים נרצחו ביריות סמוך לנצרת וגבר נוסף נורה למוות בטמרה בתוך פרק זמן קצר.",
            "sourceUrl": "https://www.ynet.co.il/news/article/ryfr88ybgx",
        },
        {
            "source": "ישראל היום - כל הכתבות",
            "category": "פלילים",
            "categoryClass": "security",
            "headline": "הרצח בטמרה מצטרף לשני נרצחים נוספים ביפיע באותו ערב",
            "originalTitle": "חשד לרצח בטמרה: גבר כבן 50 נהרג באירוע אלימות",
            "context": "מד״א קבע את מותו של גבר כבן 50 בטמרה; מוקדם יותר נרצחו שני גברים בכפר יפיע.",
            "sourceUrl": "https://www.israelhayom.co.il/news/crime/article/20694495",
        },
    ),
    (
        "tamra_yafia_triple_murder_walla_ynet_visible_regression_20260605",
        True,
        {
            "source": "וואלה חדשות",
            "category": "פלילים",
            "categoryClass": "security",
            "headline": "שלושה נרצחו בחברה הערבית בצפון בתוך כמה שעות",
            "originalTitle": "גבר נורה למוות בטמרה: שלושה נרצחים בחברה הערבית תוך שעות",
            "context": "גבר נורה למוות בטמרה, זמן קצר אחרי ששני צעירים נרצחו ביריות באזור נצרת ויפיע.",
            "sourceUrl": "https://news.walla.co.il/item/3843347",
        },
        {
            "source": "ynet - כל ערוץ החדשות",
            "category": "פלילים",
            "categoryClass": "security",
            "headline": "שלושה גברים נרצחו ביריות בתוך שעות באזור נצרת ובטמרה",
            "originalTitle": "שני צעירים נרצחו ביריות ליד נצרת, גבר נורה למוות בטמרה",
            "context": "שני צעירים נרצחו ביריות סמוך לנצרת וגבר נוסף נורה למוות בטמרה בתוך פרק זמן קצר.",
            "sourceUrl": "https://www.ynet.co.il/news/article/ryfr88ybgx",
        },
    ),
    (
        "trump_iran_uranium_ground_operation_walla_ynet_visible_regression_20260605",
        True,
        {
            "source": "וואלה חדשות - מבזקים",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "טראמפ שקל כניסה קרקעית לאיראן כדי להוציא אורניום מועשר",
            "originalTitle": "טראמפ שקל מבצע קרקעי באיראן להוצאת אורניום מועשר",
            "context": "טראמפ שקל אפשרות למבצע קרקעי באיראן שמטרתו הוצאת אורניום מועשר מתוך המדינה.",
            "sourceUrl": "https://news.walla.co.il/break/3843344",
        },
        {
            "source": "ynet - כל ערוץ החדשות",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "טראמפ הסתייג ממבצע קרקעי להוצאת אורניום מאיראן",
            "originalTitle": "טראמפ הסתייג ממבצע קרקעי להוצאת אורניום מאיראן",
            "context": "טראמפ הסתייג מאפשרות לשלוח כוחות קרקעיים כדי להוציא אורניום מועשר מאיראן.",
            "sourceUrl": "https://www.ynet.co.il/news/article/bk00w1vywme",
        },
    ),
    (
        "israel_slovenia_embassy_walla_israelhayom_visible_regression_20260604",
        True,
        {
            "source": "וואלה חדשות - חדשות בעולם",
            "category": "פוליטיקה",
            "categoryClass": "security",
            "headline": "סער מנצל ממשלה ידידותית בסלובניה לפתיחת שגרירות ישראלית",
            "originalTitle": "מיד לאחר אישור הקמת הממשלה החדשה: ישראל תפתח שגרירות בסלובניה",
            "context": "ישראל תפתח לראשונה שגרירות בלובליאנה מיד לאחר אישור ממשלת יאנז יאנשה בסלובניה.",
            "sourceUrl": "https://news.walla.co.il/item/3843320",
        },
        {
            "source": "ynet - מבזקי החדשות",
            "category": "פוליטיקה",
            "categoryClass": "security",
            "headline": "ראש ממשלת סלובניה בירך על פתיחת השגרירות הישראלית",
            "originalTitle": "ראש ממשלת סלובניה: \"מצפים לעידן חדש ביחסים עם ישראל\"",
            "context": "ראש ממשלת סלובניה בירך על פתיחת השגרירות הישראלית ואמר כי המדינה מצפה לעידן חדש ביחסים עם ישראל.",
            "sourceUrl": "https://www.ynet.co.il/news/article/bji9jij11mg",
        },
    ),
    (
        "idf_shinbet_hamas_security_apparatus_jpost_ynet_visible_regression_20260604",
        True,
        {
            "source": "The Jerusalem Post - Israel News",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "צה״ל ושב״כ חיסלו בכירי מנגנון האבטחה של חמאס בעזה",
            "originalTitle": "IDF, Shin Bet kill several Hamas General Security Apparatus officials in Gaza",
            "context": "צה״ל ושב״כ חיסלו כמה בכירים במנגנון הביטחון הכללי של חמאס בעזה, בהם גורמים שאחראים על אבטחת בכירי הארגון.",
            "sourceUrl": "https://www.jpost.com/israel-news/defense-news/article-898428",
        },
        {
            "source": "ynet - מבזקי החדשות",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "צה״ל ושב״כ חיסלו ארבעה מאבטחי בכירי חמאס",
            "originalTitle": "צה\"ל ושב\"כ: חוסלו ארבעה בכירים במנגנון האחראי גם על אבטחת בכירים בחמאס",
            "context": "צה״ל ושב״כ הודיעו על חיסול ארבעה בכירים במנגנון שאחראי בין היתר על אבטחת בכירי חמאס.",
            "sourceUrl": "https://www.ynet.co.il/news/article/b1fbhqkbgx",
        },
    ),
    (
        "israel_lebanon_hezbollah_ceasefire_guardian_nyt_rejection_visible_regression_20260604",
        True,
        {
            "source": "The Guardian Middle East",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "הפסקת האש בלבנון תלויה בעצירה מלאה של חיזבאללה",
            "originalTitle": "Israel and Lebanon agree yet another ceasefire - but can it hold?",
            "context": "ישראל ולבנון הסכימו על מסגרת להפסקת אש, אבל המשך ההסלמה תלוי בשאלה אם חיזבאללה יעצור את הפעילות בדרום.",
            "sourceUrl": "https://www.theguardian.com/news/video/2026/jun/04/israel-and-lebanon-agree-yet-another-ceasefire-but-can-it-hold-the-latest",
        },
        {
            "source": "New York Times Middle East",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "הפסקת האש בלבנון מתערערת אחרי שחיזבאללה דחה את ההסכם",
            "originalTitle": "Lebanon ceasefire faces uncertainty after Hezbollah rejection",
            "context": "חיזבאללה דחה את מסגרת הפסקת האש בין ישראל ללבנון, וההסכם נותר תלוי בהסרת האיום מהדרום.",
            "sourceUrl": "https://www.nytimes.com/live/2026/06/04/world/iran-war-trump-israel-lebanon/lebanon-ceasefire-israel-strikes",
        },
    ),
    (
        "outgoing_golani_commander_besheva_maariv_visible_regression_20260604",
        True,
        {
            "source": "בשבע - מגזין ודעות",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "מח״ט גולני היוצא אומר שהרחפנים לא משנים את הלחימה",
            "originalTitle": "\"הרחפנים הם איום, אבל הם לא מונעים מאיתנו להילחם כרגיל\"",
            "context": "אל״ם יאיר גנון סיכם את שירותו כמח״ט גולני וטען שהרחפנים הם איום משמעותי אך אינם משנים את דרך הלחימה של החטיבה.",
            "sourceUrl": "https://be7.co.il/24124",
        },
        {
            "source": "מעריב - חדשות",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "מח״ט גולני היוצא מסכם שנתיים עם 132 נופלים",
            "originalTitle": "132 נופלים בשנתיים של לחימה: האירוע הקשה שלא עוזב את מח\"ט גולני היוצא",
            "context": "מח״ט גולני היוצא סיכם שנתיים של לחימה שבהן החטיבה איבדה 132 לוחמים והתייחסה גם לאיום הרחפנים בצפון.",
            "sourceUrl": "https://www.maariv.co.il/news/military/article-1329398",
        },
    ),
    (
        "idf_chief_north_hezbollah_posture_jpost_walla_visible_regression_20260604",
        True,
        {
            "source": "The Jerusalem Post - Israel News",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "הרמטכ״ל לצפון: צה״ל פרוס מול חיזבאללה בלי מדיניות הכלה",
            "originalTitle": "IDF chief tells northern leaders army has no containment policy against Hezbollah",
            "context": "הרמטכ״ל אמר לראשי רשויות בצפון שצה״ל ערוך מול חיזבאללה ופועל ללא מדיניות הכלה.",
            "sourceUrl": "https://www.jpost.com/israel-news/defense-news/article-898406",
        },
        {
            "source": "וואלה חדשות - צבא וביטחון",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "הרמטכ״ל מבהיר לצפון: אין הכלה מול איומי חיזבאללה",
            "originalTitle": "הרמטכ״ל לראשי הרשויות בצפון: אין הכלה, נפעל בהתקפיות מול חיזבאללה",
            "context": "הרמטכ״ל הדגיש לראשי הרשויות בצפון כי צה״ל ירכז מאמץ ויפעל בהתקפיות מול איומי חיזבאללה בגבול.",
            "sourceUrl": "https://news.walla.co.il/item/3843252",
        },
    ),
    (
        "israel_lebanon_hezbollah_ceasefire_litani_live_regression_20260604",
        True,
        {
            "source": "The Jerusalem Post - Israel News",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "ישראל ולבנון קידמו הפסקת אש שמותנית בהרחקת חיזבאללה",
            "originalTitle": "Israel, Lebanon agree to ceasefire on condition of end to Hezbollah fire, US State Department says",
            "context": "ישראל ולבנון קידמו הבנות להפסקת אש בתיווך אמריקני, בתנאי שחיזבאללה יורחק מהאזור המאיים על הצפון.",
            "sourceUrl": "https://www.jpost.com/israel-news/defense-news/article-898323",
        },
        {
            "source": "מעריב - חדשות",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "ישראל ולבנון קושרות הפסקת אש לנסיגת חיזבאללה מהליטני",
            "originalTitle": "הפסקת אש מותנית בין ישראל ללבנון: תלויה בפריסת חיזבאללה מדרום לליטני",
            "context": "הפסקת האש בין ישראל ללבנון מותנית בהרחקת חיזבאללה מדרום לליטני ובמניעת ירי נוסף לעבר הצפון.",
            "sourceUrl": "https://www.maariv.co.il/news/politics/article-1329059",
        },
    ),
    (
        "israel_lebanon_hezbollah_ceasefire_walla_jpost_visible_regression_20260604",
        True,
        {
            "source": "The Jerusalem Post - Israel News",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "ישראל ולבנון קידמו אזורי פיילוט בלי חיזבאללה בדרום",
            "originalTitle": "Israel, Lebanon agree to ceasefire on condition of end to Hezbollah fire, US State Department says",
            "context": "ישראל ולבנון קידמו אזורי פיילוט להפסקת אש בדרום, בתנאי שחיזבאללה יורחק והצבא הלבנוני ייכנס לאזור.",
            "sourceUrl": "https://www.jpost.com/israel-news/defense-news/article-898323",
        },
        {
            "source": "וואלה חדשות - חדשות בעולם",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "ישראל ולבנון קידמו הפסקת אש בתנאי שחיזבאללה יורחק",
            "originalTitle": "\"הפסקת האש - תמורת הפסקת ירי חיזבאללה\": סיכומי סבב שיחות השלום בין ישראל ללבנון",
            "context": "ישראל ולבנון קידמו הפסקת אש בתיווך אמריקני, כאשר התנאי המרכזי הוא הפסקת ירי חיזבאללה והרחקתו מדרום לבנון.",
            "sourceUrl": "https://news.walla.co.il/item/3843087",
        },
    ),
    (
        "israel_lebanon_hezbollah_ceasefire_guardian_globes_inn_visible_regression_20260604",
        True,
        {
            "source": "גלובס - בארץ",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "הפסקת אש בין ישראל ללבנון הותנתה בנסיגת חיזבאללה",
            "originalTitle": "בתום סבב השיחות: ישראל ולבנון הסכימו על הפסקת אש מלאה",
            "context": "ישראל, לבנון וארה״ב הגיעו להסכם הפסקת אש, בכפוף לנסיגת פעילי חיזבאללה מהשטח שמדרום לליטני.",
            "sourceUrl": "https://www.globes.co.il/news/article.aspx?did=1001544930#utm_source=RSS",
        },
        {
            "source": "The Guardian Middle East",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "הסכם ביטחוני חדש בגבול לבנון",
            "originalTitle": "Netanayahu’s been ‘a great partner’, says Trump – as it happened",
            "context": "ישראל ולבנון הסכימו בתיווך אמריקני לחדש את הפסקת האש ולהקים אזורי ביטחון ניסיוניים בדרום לבנון, שבהם יורחקו פעילי חיזבאללה והצבא הלבנוני יקבל אחריות מלאה מדרום לליטני.",
            "sourceUrl": "https://www.theguardian.com/world/live/2026/jun/03/us-israel-iran-war-lebanon-trump-khamenei-netanyahu-hormuz-latest-news-updates",
        },
    ),
    (
        "israel_lebanon_iran_out_inn_globes_visible_regression_20260604",
        True,
        {
            "source": "ערוץ 7 / INN עברית",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "לייטר: ישראל, לבנון וארה״ב פועלות להרחיק את איראן",
            "originalTitle": "שגריר ישראל בארה\"ב: ישראל, לבנון ואמריקה מאוחדות כדי להשאיר את איראן בחוץ",
            "context": "שגריר ישראל בארה״ב יחיאל לייטר הציג את הרחקת איראן כיעד מרכזי במגעים סביב הפסקת האש בין ישראל ללבנון.",
            "takeaway": "המסר מציב את חיזבאללה ואיראן כקו אדום גם אם מתקדם הסדר בחסות אמריקנית.",
            "sourceUrl": "https://www.inn.co.il/flashes/1116165",
        },
        {
            "source": "גלובס - בארץ",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "הפסקת אש בין ישראל ללבנון הותנתה בנסיגת חיזבאללה",
            "originalTitle": "בתום סבב השיחות: ישראל ולבנון הסכימו על הפסקת אש מלאה",
            "context": "ישראל, לבנון וארה״ב הגיעו להסכם הפסקת אש, בכפוף לנסיגת פעילי חיזבאללה מהשטח שמדרום לליטני.",
            "sourceUrl": "https://www.globes.co.il/news/article.aspx?did=1001544930#utm_source=RSS",
        },
    ),
    (
        "fox_noy_hasadeh_business_live_regression_20260603",
        True,
        {
            "source": "גלובס - שוק ההון",
            "category": "כלכלה",
            "categoryClass": "money",
            "headline": "הראל ויזל בוחן כניסה לשוק המזון דרך נוי השדה",
            "originalTitle": "הראל ויזל בוחן כניסה לשוק המזון דרך רכישת נוי השדה",
            "context": "קבוצת פוקס של הראל ויזל בוחנת רכישת פעילות נוי השדה כדי להיכנס לשוק המזון הטרי.",
            "sourceUrl": "https://www.globes.co.il/news/article.aspx?did=1001544823#utm_source=RSS",
        },
        {
            "source": "דה מרקר - שוק ההון",
            "category": "כלכלה",
            "categoryClass": "money",
            "headline": "פוקס בוחנת רכישת רשת נוי השדה",
            "originalTitle": "פוקס בוחנת רכישת רשת נוי השדה",
            "context": "פוקס בוחנת עסקה לרכישת רשת המזון נוי השדה כחלק מהרחבת הפעילות הקמעונאית שלה.",
            "sourceUrl": "https://www.themarker.com/markets/2026-06-03/ty-article/.premium/0000019e-8c29-d0a9-a7df-bdbb2e500000",
        },
    ),
    (
        "israir_slovenia_landing_diversion_live_regression_20260603",
        True,
        {
            "source": "ynet - מבזקי החדשות",
            "category": "פוליטיקה",
            "categoryClass": "security",
            "headline": "טיסת ישראייר הוסטה מלובליאנה לזאגרב",
            "originalTitle": "טיסת ישראייר ללובליאנה הוסטה לזאגרב",
            "context": "טיסת ישראייר לא הורשתה לנחות בלובליאנה והוסטה לזאגרב בעקבות החלטת הרשויות בסלובניה.",
            "sourceUrl": "https://www.ynet.co.il/news/article/hjmahpteme",
        },
        {
            "source": "N12 - בעולם",
            "category": "פוליטיקה",
            "categoryClass": "security",
            "headline": "סלובניה חסמה נחיתה לישראייר",
            "originalTitle": "סלובניה חסמה נחיתה לטיסת ישראייר",
            "context": "הרשויות בסלובניה חסמו נחיתה של טיסת ישראייר בלובליאנה, והמטוס נחת לבסוף בזאגרב.",
            "sourceUrl": "https://www.mako.co.il/news-world/2026_q2/Article-58489083cac8e91026.htm",
        },
    ),
    (
        "us_iran_tanker_hellfire_live_regression_20260603",
        True,
        {
            "source": "וואלה חדשות - חדשות בעולם",
            "category": "ביטחון",
            "headline": "ארה״ב השביתה מכלית בדרך לאיראן בטיל הלפייר",
            "originalTitle": "המתיחות נמשכת: ארה\"ב ניטרלה מכלית נפט שהייתה בדרכה לאיראן",
            "context": "כוחות אמריקניים השביתו במפרץ הפרסי את מכלית M/T Lexie אחרי שהתעלמה במשך יממה מהוראות בדרכה למסוף הנפט ח׳ארג באיראן.",
            "sourceUrl": "https://news.walla.co.il/item/3842812",
        },
        {
            "source": "BBC World",
            "category": "ביטחון",
            "headline": "ארה״ב שיתקה מכלית בדרך לאיראן כחלק מהמצור במצר הורמוז",
            "originalTitle": "US says it fired missile at Iran-bound oil tanker",
            "context": "הכוחות האמריקניים ירו על מכלית שהייתה בדרכה לאיראן כחלק מאכיפת המצור הימי במצר הורמוז.",
            "sourceUrl": "https://www.bbc.com/news/articles/c5yx135yg53o",
        },
    ),
    (
        "us_iran_tanker_guardian_walla_live_regression_20260603",
        True,
        {
            "source": "The Guardian Middle East",
            "category": "ביטחון",
            "headline": "ארה״ב השביתה מכלית בדרך לאיראן והחריפה את משבר הורמוז",
            "originalTitle": "Guardian US fires missile at tanker attempting to reach Iran amid strait of Hormuz standoff",
            "context": "כוחות אמריקניים ירו על מכלית שניסתה להגיע לאיראן במסגרת העימות סביב מצר הורמוז.",
            "sourceUrl": "https://www.theguardian.com/world/2026/jun/03/us-fires-missile-tanker-strait-of-hormuz",
        },
        {
            "source": "וואלה חדשות - חדשות בעולם",
            "category": "ביטחון",
            "headline": "ארה״ב השביתה מכלית בדרך לאיראן בטיל הלפייר",
            "originalTitle": "המתיחות נמשכת: ארה\"ב ניטרלה מכלית נפט שהייתה בדרכה לאיראן",
            "context": "כוחות אמריקניים השביתו במפרץ הפרסי מכלית שהייתה בדרכה למסוף הנפט ח׳ארג באיראן.",
            "sourceUrl": "https://news.walla.co.il/item/3842812",
        },
    ),
    (
        "us_iran_tanker_guardian_current_headline_url_20260603",
        True,
        {
            "source": "The Guardian Middle East",
            "category": "ביטחון",
            "headline": "ארה״ב ואיראן חידשו תקיפות סביב מצר הורמוז והמפרץ",
            "originalTitle": "US and Iran launch fresh strikes amid stalled ceasefire talks",
            "context": "ארה״ב השביתה מכלית שהתקרבה לאיראן, תקפה מטרות בקשם והדפה טילים וכטב״מים לעבר כוויית ובחריין.",
            "sourceUrl": "https://www.theguardian.com/world/2026/jun/03/us-fires-missile-tanker-strait-of-hormuz",
        },
        {
            "source": "וואלה חדשות - מבזקים",
            "category": "ביטחון",
            "headline": "מטוס אמריקני השבית מכלית בדרך למסוף הנפט באיראן",
            "originalTitle": "פיקוד המרכז של ארה״ב: מכלית נפט שהייתה בדרכה לאיראן נוטרלה באמצעות טיל הלפייר",
            "context": "המכלית M/T Lexie המשיכה לעבר האי ח'ארג אחרי אזהרות אמריקניות, וטיל הלפייר פגע בחדר המנוע והשבית את הספינה.",
            "sourceUrl": "https://news.walla.co.il/break/3842815",
        },
    ),
    (
        "us_iran_gulf_exchange_kuwait_bahrain_20260603",
        True,
        {
            "source": "BBC World",
            "category": "ביטחון",
            "headline": "ארה״ב תקפה עמדת שליטה איראנית בקשם אחרי ירי למפרץ",
            "originalTitle": "US says it launched 'self-defense' strikes on Iranian island",
            "context": "פיקוד המרכז האמריקני תקף באי קשם תחנת שליטה איראנית, לאחר שטילים וכטב״מים שוגרו לעבר כלי שיט ומדינות מפרץ כמו כווית ובחריין.",
            "sourceUrl": "https://www.bbc.com/news/articles/c5yx135yg53o?at_medium=RSS&at_campaign=rss",
        },
        {
            "source": "מעריב - חדשות",
            "category": "ביטחון",
            "headline": "איראן הרחיבה את תגובת המפרץ לכווית ולבחריין",
            "originalTitle": "לילה סוער במפרץ: ארה\"ב פעלה בהורמוז - איראן תקפה בכווית ובחריין",
            "context": "אחרי פעולה אמריקנית נגד מכלית שניסתה להגיע לאיראן, כווית ובחריין הפעילו מערכי הגנה והתרעות מפני טילים וכטב״מים.",
            "sourceUrl": "https://www.maariv.co.il/news/world/article-1328648",
        },
    ),
    (
        "north_reconstruction_13b_live_regression_20260603",
        True,
        {
            "source": "וואלה חדשות",
            "category": "ביטחון",
            "headline": "הממשלה אישרה תוכנית מיגון ושיקום של 13 מיליארד שקל לצפון",
            "originalTitle": "הממשלה אישרה 13 מיליארד ש\"ח לשיקום הצפון",
            "context": "הממשלה אישרה תוכנית מיגון ושיקום ליישובי קו העימות בצפון, כולל ממ״דים, מקלטים, כבישים ושירותי רפואה.",
            "sourceUrl": "https://news.walla.co.il/item/3842802",
        },
        {
            "source": "The Jerusalem Post - Israel News",
            "category": "ביטחון",
            "headline": "הממשלה אישרה תוספת של 13 מיליארד שקל ליישובי הצפון",
            "originalTitle": "Gov't greenlights NIS 13b. for shelters, infrastructure in Israel's North",
            "context": "הממשלה אישרה תוספת של 13 מיליארד שקל למקלטים, תשתיות ושיקום יישובי הצפון סמוך לגבול לבנון.",
            "sourceUrl": "https://www.jpost.com/israel-news/politics-and-diplomacy/article-898166",
        },
    ),
    (
        "idf_south_lebanon_village_evacuation_live_regression_20260603",
        True,
        {
            "source": "וואלה חדשות - מבזקים",
            "category": "ביטחון",
            "headline": "צה״ל הזהיר שישה כפרים בדרום לבנון להתפנות לפני תקיפה",
            "context": "דובר צה״ל בערבית פרסם אזהרת פינוי דחופה לתושבי שישה כפרים בדרום לבנון לפני תקיפה",
            "sourceUrl": "https://news.walla.co.il/break/3842848",
        },
        {
            "source": "ynet - מבזקי החדשות",
            "category": "ביטחון",
            "headline": "צה״ל קרא לפינוי כפרים בדרום לבנון",
            "context": "צה״ל פרסם אזהרת פינוי לשני כפרים באזור צידון ולכפר מצפון לצור",
            "sourceUrl": "https://www.ynet.co.il/news/article/hkeqhstgzg",
        },
    ),
    (
        "netanyahu_hezbollah_drone_solution_north_live_regression_20260603",
        True,
        {
            "source": "The Jerusalem Post - Israel News",
            "category": "ביטחון",
            "headline": "נתניהו מבטיח פתרון קרוב לאיום רחפני חיזבאללה",
            "context": "נתניהו אמר לראשי מועצות בצפון שפתרון לאיום רחפני חיזבאללה ייושם בימים הקרובים",
            "sourceUrl": "https://www.jpost.com/israel-news/article-898177",
        },
        {
            "source": "ישראל היום - כל הכתבות",
            "category": "ביטחון",
            "headline": "נתניהו הבטיח ליישובי הצפון פתרון קרוב לרחפני הנפץ",
            "context": "ראש הממשלה אמר לתושבי הצפון שהמערכת להתמודדות עם רחפני הנפץ של חיזבאללה צפויה להיות מיושמת בקרוב",
            "sourceUrl": "https://www.israelhayom.co.il/news/defense/article/20678235",
        },
    ),
    (
        "trump_netanyahu_beirut_strike_cancelled_cross_source",
        True,
        {
            "source": "The Jerusalem Post - Israel News",
            "category": "פוליטיקה",
            "headline": "נתניהו ביטל תקיפה בביירות בלחץ טראמפ ועורר ביקורת בישראל",
            "originalTitle": "'Time to say no to Trump': Israeli officials condemn Netanyahu's decision to cancel Lebanon strike",
            "context": "נתניהו ביטל תוכנית לתקיפה ישראלית בביירות לאחר שטראמפ דרש לעצור את המהלך. פוליטיקאים ואנשי ביטחון בישראל טענו שההחלטה מצמצמת את חופש הפעולה מול חיזבאללה ומחזקת תלות בוושינגטון.",
            "sourceUrl": "https://www.jpost.com/israel-news/politics-and-diplomacy/article-898056",
        },
        {
            "source": "וואלה חדשות - חדשות בעולם",
            "category": "ביטחון",
            "headline": "טראמפ בלם תוכנית ישראלית לתקוף בביירות",
            "originalTitle": "\"אתה משוגע וכפוי טובה\": שיחת הקללות בין טראמפ לנתניהו",
            "context": "טראמפ גער בנתניהו בשיחה חריפה על רקע ההסלמה בלבנון והחשש מפגיעה במגעים עם איראן. בעקבות הלחץ האמריקני, ישראל ויתרה בשלב זה על תקיפה שתוכננה בביירות.",
            "sourceUrl": "https://news.walla.co.il/item/3842531",
        },
    ),
    (
        "trump_netanyahu_beirut_strike_cancelled_be7_ynet_live_regression",
        True,
        {
            "source": "בשבע - מגזין ודעות",
            "category": "ביטחון",
            "headline": "טראמפ בלם תקיפה ישראלית בדאחייה אחרי איום איראני",
            "originalTitle": "טראמפ מנע תקיפה ישראלית בדאחייה בעקבות איומי איראן",
            "context": "איראן איימה להפסיק את השיחות עם ארה״ב ולשקול חסימת מצרים ימיים; בעקבות זאת טראמפ דרש מנתניהו לעצור את הפעולה בביירות.",
            "sourceUrl": "https://be7.co.il/23947",
        },
        {
            "source": "ynet - מבזקי החדשות",
            "category": "ביטחון",
            "headline": "ביקורת בליכוד על ביטול התקיפה בביירות",
            "originalTitle": "ביקורת בליכוד על ביטול התקיפה בביירות",
            "context": "ח״כ משה סעדה תקף את ביטול התקיפות בדאחייה בעקבות הנחיית דונלד טראמפ, וטען כי מדיניות ההכלה מול האיום בלבנון מסוכנת לישראל.",
            "sourceUrl": "https://www.ynet.co.il/news/article/hjwesghlge",
        },
    ),
    (
        "attorney_general_split_bill_cross_source",
        True,
        {
            "source": "The Jerusalem Post - Israel News",
            "category": "פוליטיקה",
            "headline": "חוק פיצול היועמ״שית עבר בקריאה ראשונה בכנסת",
            "originalTitle": "Bill that would split role of attorney-general passes first Knesset reading",
            "context": "הכנסת אישרה בקריאה ראשונה הצעה לפצל את תפקיד היועץ המשפטי לממשלה ליועץ משפטי ולתובע כללי, ולהרחיב את יכולת הממשלה לקבוע מינוי וייצוג משפטי.",
            "sourceUrl": "https://www.jpost.com/israel-news/politics-and-diplomacy/article-898054",
        },
        {
            "source": "וואלה חדשות - פוליטי-מדיני",
            "category": "משפט",
            "headline": "חוק פיצול היועמ״שית עבר בקריאה ראשונה למרות אזהרות מערכת המשפט",
            "originalTitle": "בקריאה ראשונה: מליאת הכנסת אישרה את הצעת החוק לפיצול תפקיד היועמ\"שית",
            "context": "מליאת הכנסת אישרה בקריאה ראשונה את הצעת החוק לפיצול תפקיד היועץ המשפטי לממשלה, ברוב של 65 תומכים מול 47 מתנגדים.",
            "sourceUrl": "https://news.walla.co.il/item/3842526",
        },
    ),
    (
        "attorney_general_split_bill_ynet_jpost_live_regression",
        True,
        {
            "source": "ynet - כל ערוץ החדשות",
            "category": "פוליטיקה",
            "headline": "הכנסת אישרה בקריאה ראשונה את פיצול תפקיד היועמ״ש",
            "originalTitle": "הכנסת אישרה בקריאה ראשונה את פיצול תפקיד היועמ\"ש",
            "context": "הכנסת אישרה בקריאה ראשונה את פיצול תפקיד היועץ המשפטי לממשלה ליועץ משפטי ולתובע כללי. המהלך הוא נדבך מרכזי בתוכנית הקואליציה לשינוי יחסי הממשלה ומערכת המשפט.",
            "sourceUrl": "https://www.ynet.co.il/news/article/hjmply3efe",
        },
        {
            "source": "The Jerusalem Post - Israel News",
            "category": "פוליטיקה",
            "headline": "חוק פיצול היועמ״שית עבר בקריאה ראשונה בכנסת",
            "originalTitle": "Bill that would split role of attorney-general passes first Knesset reading",
            "context": "הכנסת אישרה בקריאה ראשונה הצעה לפצל את תפקיד היועץ המשפטי לממשלה ליועץ משפטי ולתובע כללי, ולהרחיב את יכולת הממשלה לקבוע מינוי וייצוג משפטי.",
            "sourceUrl": "https://www.jpost.com/israel-news/politics-and-diplomacy/article-898054",
        },
    ),
    (
        "us_southern_iran_strikes_cross_language",
        True,
        {
            "source": "New York Times Middle East",
            "category": "ביטחון",
            "headline": "ארה״ב ביצעה תקיפות הגנה עצמית בדרום איראן",
            "originalTitle": "U.S. Carries Out Renewed Strikes in Southern Iran",
            "context": "פיקוד המרכז האמריקני מסר כי תקף אתרי שיגור טילים וסירות איראניות שניסו להניח מוקשים, כדי להגן על כוחותיו בזמן הפסקת האש. התקיפות ליד בנדר עבאס הגיעו במקביל לשיחות בדוחא על סיום המלחמה ועל פתיחת מצר הורמוז.",
            "sourceUrl": "https://www.nytimes.com/example-us-iran-strikes",
        },
        {
            "source": "וואלה חדשות - מבזקים",
            "category": "ביטחון",
            "headline": "ארה״ב אישרה תקיפות הגנתיות בתוך איראן",
            "originalTitle": "ארה\"ב אישרה כי כוחותיה ביצעו הלילה תקיפות \"להגנה עצמית\" בשטח איראן",
            "context": "פיקוד המרכז האמריקני אישר שכוחות ארה״ב תקפו בתוך איראן אתרי שיגור טילים וסירות שניסו להניח מוקשים. הפיקוד הציג את הפעולה כהגנה עצמית במהלך הפסקת האש.",
            "sourceUrl": "https://news.walla.co.il/break/example-us-iran-strikes",
        },
    ),
    (
        "hormuz_talks_background_not_same_as_strike",
        False,
        {
            "source": "The Guardian Middle East",
            "category": "ביטחון",
            "headline": "רוביו מאיים לפתוח את הורמוז בזמן שיחות עם איראן",
            "originalTitle": "Tehran expresses ‘resolute support’ for Hezbollah – as it happened",
            "context": "שר החוץ האמריקני מרקו רוביו אמר שמצר הורמוז חייב להיפתח כך או אחרת, אחרי תקיפות אמריקניות בדרום איראן. במקביל, נציגים איראניים הגיעו לדוחא לשיחות על הסכם אפשרי.",
            "sourceUrl": "https://www.theguardian.com/example-hormuz-talks",
        },
        {
            "source": "New York Times Middle East",
            "category": "ביטחון",
            "headline": "ארה״ב ביצעה תקיפות הגנה עצמית בדרום איראן",
            "originalTitle": "U.S. Carries Out Renewed Strikes in Southern Iran",
            "context": "פיקוד המרכז האמריקני מסר כי תקף אתרי שיגור טילים וסירות איראניות שניסו להניח מוקשים ליד בנדר עבאס.",
            "sourceUrl": "https://www.nytimes.com/example-us-iran-strikes",
        },
    ),
    (
        "weather_shavuot_rain_wind",
        True,
        {
            "source": "וואלה חדשות",
            "category": "חדשות",
            "headline": "גשם ורוחות ילוו את ערב שבועות בצפון ובמרכז",
            "originalTitle": "חג שבועות חורפי: גשם מקומי ורוחות ערות ברחבי הארץ",
            "context": "היום ומחר צפויה ירידה בטמפרטורות, עם גשם מקומי בצפון ובמרכז ורוחות ערות.",
            "sourceUrl": "https://news.walla.co.il/item/3839781",
        },
        {
            "source": "מעריב - חדשות",
            "category": "חדשות",
            "headline": "גשם ורוחות צפויים בערב חג השבועות",
            "originalTitle": "רגע לפני ערב חג השבועות - שינוי מפתיע במזג האוויר",
            "context": "בערב חג השבועות צפויה ירידה נוספת בטמפרטורות. בצפון ובמרכז צפויים גשמים ורוחות.",
            "sourceUrl": "https://www.maariv.co.il/news/weather/article-1323962",
        },
    ),
    (
        "same_concert_move",
        True,
        {
            "source": "וואלה חדשות",
            "category": "תרבות",
            "headline": "נשף רוק של אביב גפן הוקדם ל־17 ביוני",
            "context": "המופע הוקדם בגלל שלוש הופעות ענק באזור גוש דן באותו שבוע.",
            "sourceUrl": "https://news.walla.co.il/example-a",
        },
        {
            "source": "ישראל היום - כל הכתבות",
            "category": "תרבות",
            "headline": "נשף רוק הוקדם בגלל שלוש הופעות ענק בגוש דן",
            "context": "אביב גפן הזיז את הנשף ל־17 ביוני כדי לא להתנגש עם עומס מופעים גדול בגוש דן.",
            "sourceUrl": "https://www.israelhayom.co.il/example-b",
        },
    ),
    (
        "lod_residential_fire_cross_category",
        True,
        {
            "source": "חדשות 12",
            "category": "חדשות",
            "headline": "18 דיירים חולצו משריפה בבניין בלוד",
            "originalTitle": "18 דיירים חולצו משריפה בבניין מגורים בלוד",
            "context": "צוותי כבאות חילצו 18 דיירים מבניין מגורים בלוד לאחר שפרצה בו שריפה.",
            "sourceUrl": "https://www.mako.co.il/news-example-lod-fire",
        },
        {
            "source": "מעריב - חדשות",
            "category": "פלילים",
            "headline": "שריפה בבניין בלוד הסתיימה בחילוץ דיירים",
            "originalTitle": "שריפה פרצה בבניין מגורים בלוד; דיירים חולצו מהמקום",
            "context": "כוחות הכיבוי פינו דיירים מבניין בלוד בעקבות שריפה שפרצה במקום.",
            "sourceUrl": "https://www.maariv.co.il/news/israel/example-lod-fire",
        },
    ),
    (
        "kiryat_shmona_rocket_cross_source",
        True,
        {
            "source": "וואלה חדשות",
            "category": "ביטחון",
            "headline": "רקטה פגעה במרכז קריית שמונה וגרמה נזק כבד לעסקים",
            "originalTitle": "לילה לא שקט בצפון: פגיעה ישירה בקריית שמונה - נזק כבד לעסקים, אין נפגעים",
            "context": "במהלך הלילה נורו עשרה שיגורים מלבנון לעבר קריית שמונה והגליל העליון, ותשעה מהם יורטו.",
            "sourceUrl": "https://news.walla.co.il/item/example-k8",
        },
        {
            "source": "הארץ - חדשות",
            "category": "ביטחון",
            "headline": "רקטה נפלה במרכז קריית שמונה אחרי מטח מלבנון",
            "originalTitle": "ירי בלתי פוסק לעבר הצפון: רקטה נפלה בקריית שמונה",
            "context": "רקטה ששוגרה מלבנון נפלה בקריית שמונה וגרמה נזק לחנויות ולעסקים, ללא נפגעים.",
            "sourceUrl": "https://www.haaretz.co.il/example-k8",
        },
    ),
    (
        "yirka_samer_halabi_murder_cross_source",
        True,
        {
            "source": "ynet - מבזקי החדשות",
            "category": "פלילים",
            "headline": "סאמר חלבי בן ה־24 נרצח בירכא במהלך חגיגת יום הולדת",
            "originalTitle": "הנרצח בירכא: תושב היישוב סאמר חלבי",
            "context": "סאמר חלבי, בן 24 מירכא, נורה למוות במהלך חגיגת יום הולדת ביישוב.",
            "sourceUrl": "https://www.ynet.co.il/news/article/example-yirka",
        },
        {
            "source": "וואלה חדשות - מבזקים",
            "category": "פלילים",
            "headline": "בן 24 נרצח בירכא והירי נשאר ללא חשודים",
            "originalTitle": "בן 24 נורה למוות בירכא; המשטרה פתחה בחקירה",
            "context": "גבר בן 24 מירכא נורה למוות, והמשטרה טרם איתרה חשודים בירי.",
            "sourceUrl": "https://news.walla.co.il/break/example-yirka",
        },
    ),
    (
        "iran_hardliners_against_us_deal_cross_source",
        True,
        {
            "source": "ynet - כל ערוץ החדשות",
            "category": "ביטחון",
            "headline": "הקיצונים באיראן לוחצים על חמינאי לבלום הסכם עם ארה״ב",
            "originalTitle": "עצרות המונים ומכתב מתריס למנהיג העליון: הקיצונים באיראן שפועלים נגד ההסכם",
            "context": "פלג קיצוני בהנהגה האיראנית מפעיל לחץ על חמינאי נגד הסכם עם ארה״ב, כולל עצרות ומכתב שמאשים את צוות המשא ומתן בפיוס יתר.",
            "sourceUrl": "https://www.ynet.co.il/news/article/example-iran-hardliners",
        },
        {
            "source": "N12 - בעולם",
            "category": "ביטחון",
            "headline": "המחנה הקיצוני באיראן לוחץ נגד הסכם עם ארה״ב",
            "originalTitle": "המאבק בתוך איראן נגד ההסכם: טראמפ חייב לדעת, טהראן קובעת את התנאים",
            "context": "גורמים במחנה הקיצוני בטהראן דורשים להקשיח תנאים מול טראמפ ולמנוע פשרה מהירה במשא ומתן עם ארה״ב.",
            "sourceUrl": "https://www.mako.co.il/news-world/example-iran-hardliners",
        },
    ),
    (
        "zaporizhzhia_drone_nuclear_plant_cross_category",
        True,
        {
            "source": "מעריב - מבזקים",
            "category": "אקטואליה בעולם",
            "headline": "כטב״ם פגע במבנה טורבינה בתחנת הכוח הגרעינית זפוריז׳יה",
            "originalTitle": "הסוכנות הבינלאומית לאנרגיה אטומית: כטב\"ם פגע במבנה טורבינה בתחנת כוח גרעינית באוקראינה",
            "context": "סבא״א קיבלה עדכון מתחנת הכוח הגרעינית זפוריז׳יה באוקראינה שלפיו כטב״ם פגע במבנה טורבינה וגרם לחור בקיר.",
            "sourceUrl": "https://www.maariv.co.il/breaking-news/article-1327267",
        },
        {
            "source": "וואלה חדשות - מבזקים",
            "category": "ביטחון",
            "headline": "כטב״ם אוקראיני פגע בתחנת הכוח הגרעינית בזפוריז׳יה",
            "originalTitle": "כטב\"ם אוקראיני פגע בתחנת כוח רוסית",
            "context": "כטב״ם אוקראיני פגע בתחנת הכוח הגרעינית בזפוריז׳יה והעלה חשש סביב בטיחות המתקן.",
            "sourceUrl": "https://news.walla.co.il/break/3841879",
        },
    ),
    (
        "trump_iran_nuclear_agreement_terms_cross_source",
        True,
        {
            "source": "ישראל היום - כל הכתבות",
            "category": "ביטחון",
            "headline": "טראמפ עצר את הסכם איראן ודרש פיקוח גרעיני הדוק יותר",
            "originalTitle": "בלם את ההסכם ברגע האחרון: הדרישות החדשות שהציב טראמפ לאיראנים",
            "context": "טראמפ בלם את החתימה על מזכר ההבנות עם איראן ודרש להקשיח סעיפים על פיקוח גרעיני ועל פתיחת מצר הורמוז.",
            "sourceUrl": "https://www.israelhayom.co.il/example-trump-iran-terms",
        },
        {
            "source": "וואלה חדשות - מבזקים",
            "category": "ביטחון",
            "headline": "טראמפ טוען שאיראן הסכימה לוותר על נשק גרעיני",
            "originalTitle": "טראמפ לרשת פוקס: איראן הסכימה לא לפתח ולא לרכוש נשק גרעיני",
            "context": "טראמפ אמר שהסכם איראן יתקדם רק אם טהרן תוותר גם על רכישה עתידית של נשק גרעיני ותעמוד בתנאי הגרעין האמריקניים.",
            "sourceUrl": "https://news.walla.co.il/break/example-trump-iran-nuclear",
        },
    ),
    (
        "us_iran_hormuz_base_attacks_cross_source",
        True,
        {
            "source": "BBC World",
            "category": "ביטחון",
            "headline": "ארה״ב תקפה מכ״מים איראניים אחרי ירי באזור הורמוז",
            "context": "ארה״ב תקפה מכ״מים וסוללות באזור הורמוז לאחר ירי לעבר כוחות אמריקניים במפרץ.",
            "sourceUrl": "https://www.bbc.com/news/articles/crlpy8n7pr6o",
        },
        {
            "source": "The Guardian Middle East",
            "category": "ביטחון",
            "headline": "איראן טוענת שתקפה בסיס אמריקאי באזור המפרץ",
            "context": "איראן הציגה את הירי באזור המפרץ כתגובה לעימות עם ארה״ב סביב הורמוז והתקיפות האמריקניות.",
            "sourceUrl": "https://www.theguardian.com/world/2026/jun/01/iran-strikes-us-military-base-kuwait-iranian-air-defences",
        },
    ),
    (
        "kahlon_unetcredit_conviction_cross_category",
        True,
        {
            "source": "The Jerusalem Post - Israel News",
            "category": "כלכלה",
            "headline": "משה כחלון הורשע בעבירת דיווח בפרשת יונט קרדיט",
            "originalTitle": "Former finance minister Kahlon convicted of reporting offense in UnetCredit collapse case",
            "context": "משה כחלון הורשע במסגרת הסדר טיעון בכך שלא דאג שחריגות כספיות חמורות ביונט קרדיט ידווחו לציבור כשכיהן כיו״ר החברה.",
            "sourceUrl": "https://www.jpost.com/israel-news/politics-and-diplomacy/article-897837",
        },
        {
            "source": "דה מרקר - כל הכתבות",
            "category": "משפט",
            "headline": "משה כחלון הורשע בהסתרת מידע בפרשת יונט קרדיט",
            "context": "גם שר אוצר לשעבר נבחן כחוסם מידע לציבור כשהוא יושב בראש חברה ציבורית.",
            "sourceUrl": "https://www.themarker.com/law/example-unetcredit-kahlon",
        },
    ),
    (
        "kahlon_unetcredit_walla_jpost_live_duplicate",
        True,
        {
            "source": "וואלה חדשות",
            "category": "משפט",
            "headline": "משה כחלון הורשע בפרשת יונט קרדיט",
            "originalTitle": "משה כחלון הורשע במסגרת הסדר טיעון: \"לא הביא את מלוא המידע לידיעת הדירקטוריון והציבור\"",
            "context": "משה כחלון הודה והורשע לפי חוק ניירות ערך על תקופתו כיו״ר יונט קרדיט. ההסדר מבקש מאסר על תנאי, קנס של 180 אלף שקל והגבלת כהונה בחברה ציבורית ל־18 חודשים.",
            "sourceUrl": "https://news.walla.co.il/item/3841967",
        },
        {
            "source": "The Jerusalem Post - Israel News",
            "category": "כלכלה",
            "headline": "משה כחלון הורשע בעבירת דיווח בפרשת יונט קרדיט",
            "originalTitle": "Former finance minister Kahlon convicted of reporting offense in UnetCredit collapse case",
            "context": "משה כחלון הורשע במסגרת הסדר טיעון על הסתרת מידע מיונט קרדיט מציבור המשקיעים בזמן שכיהן כיו״ר החברה.",
            "sourceUrl": "https://www.jpost.com/israel-news/politics-and-diplomacy/article-897837",
        },
    ),
    (
        "knesset_dissolution_first_reading_cross_source",
        True,
        {
            "source": "The Jerusalem Post - Israel News",
            "category": "פוליטיקה",
            "headline": "פיזור הכנסת עבר בקריאה ראשונה ללא מתנגדים",
            "originalTitle": "Bill to dissolve Knesset passes first reading, advancing process to move up elections",
            "context": "הצעת הקואליציה לפיזור הכנסת אושרה במליאה ברוב של 106 מול 0, על רקע המשבר מול המפלגות החרדיות סביב חוק הגיוס. מועד הבחירות ייקבע לפני הקריאות השנייה והשלישית.",
            "sourceUrl": "https://www.jpost.com/israel-news/politics-and-diplomacy/article-898048",
        },
        {
            "source": "הארץ - חדשות",
            "category": "פוליטיקה",
            "headline": "הכנסת אישרה בקריאה ראשונה את חוק פיזורה",
            "originalTitle": "הכנסת אישרה בקריאה ראשונה את הצעת החוק לפיזורה",
            "context": "הכנסת אישרה בקריאה ראשונה את הצעת חוק פיזורה ברוב של 106 תומכים וללא מתנגדים. מועד הבחירות האפשרי נע בין 8 בספטמבר ל־20 באוקטובר, והקואליציה תקבע תאריך סופי לפני הקריאות הבאות.",
            "sourceUrl": "https://www.haaretz.co.il/news/politi/2026-06-02/ty-article/0000019e-8470-da5c-a9bf-df7e038a0000",
        },
    ),
    (
        "trump_cancelled_beirut_strike_cross_source",
        True,
        {
            "source": "וואלה חדשות - חדשות בעולם",
            "category": "ביטחון",
            "headline": "טראמפ בלם תוכנית ישראלית לתקוף בביירות",
            "originalTitle": "\"אתה משוגע וכפוי טובה\": שיחת הקללות בין טראמפ לנתניהו",
            "context": "טראמפ עצר תוכנית ישראלית לתקוף בביירות במסגרת העימות מול חיזבאללה, אחרי שיחה קשה עם נתניהו ועל רקע המו״מ האמריקני עם איראן.",
            "sourceUrl": "https://news.walla.co.il/item/3842531",
        },
        {
            "source": "The Jerusalem Post - Israel News",
            "category": "ביטחון",
            "headline": "בכירים בישראל תקפו את ביטול התקיפה בביירות בלחץ טראמפ",
            "originalTitle": "Time to say no to Trump: Israeli officials condemn Netanyahu's decision to cancel Lebanon strike",
            "context": "בכירים בישראל מתחו ביקורת על החלטת נתניהו לבטל תקיפה בביירות בעקבות לחץ מטראמפ, כחלק מאותו אירוע ביטול תקיפה מול חיזבאללה.",
            "sourceUrl": "https://www.jpost.com/israel-news/politics-and-diplomacy/article-898056",
        },
    ),
    (
        "us_iran_tanker_not_kuwait_air_defense_20260603",
        False,
        {
            "source": "The Guardian Middle East",
            "category": "ביטחון",
            "headline": "ארה״ב השביתה מכלית בדרך לאיראן והחריפה את משבר הורמוז",
            "originalTitle": "US fires missile at tanker attempting to reach Iran amid strait of Hormuz standoff",
            "context": "כוחות אמריקניים ירו טיל הלפייר לעבר חדר המנוע של מכלית שניסתה להגיע לאיראן אחרי 24 שעות של אזהרות.",
            "sourceUrl": "https://www.theguardian.com/world/2026/jun/03/us-fires-missile-tanker-strait-of-hormuz",
        },
        {
            "source": "מעריב - מבזקים",
            "category": "ביטחון",
            "headline": "כווית הפעילה הגנה אווירית מול טילים וכטב״מים",
            "originalTitle": "צבא כווית: מערכות ההגנה פועלות שוב ליירוט מתקפת טילים וכטב\"מים",
            "context": "צבא כווית הודיע שמערכות ההגנה האווירית פועלות נגד טילים וכטב״מים עוינים כחלק מהסלמה אזורית במפרץ.",
            "sourceUrl": "https://www.maariv.co.il/breaking-news/article-1328644",
        },
    ),
    (
        "trump_hormuz_leverage_not_written_nuclear_terms_20260603",
        False,
        {
            "source": "New York Times Middle East",
            "category": "ביטחון",
            "headline": "טראמפ זלזל באיום האיראני לסגור את מצר הורמוז",
            "originalTitle": "Trump Underestimated Iran’s Threat to Close the Strait of Hormuz",
            "context": "ממשל טראמפ העריך בחסר את יכולת איראן להפוך את איום הורמוז למנוף אסטרטגי במגעים מול וושינגטון.",
            "sourceUrl": "https://www.nytimes.com/2026/06/02/us/politics/trump-iran-strait-of-hormuz.html",
        },
        {
            "source": "ישראל היום - כל הכתבות",
            "category": "ביטחון",
            "headline": "טראמפ דורש מאיראן התחייבויות גרעין כתובות לפני הסכם",
            "originalTitle": "טראמפ דורש התחייבויות כתובות מאיראן לפני הסכם גרעין",
            "context": "הבית הלבן דורש מאיראן ויתורים כתובים ומפורטים בנושא הגרעין לפני הסכם ראשוני ומסרב לשחרר נכסים לפני ביצוע התחייבויות.",
            "sourceUrl": "https://www.israelhayom.co.il/news/world-news/middle-east/article/20677467",
        },
    ),
    (
        "different_weather_city_forecast",
        False,
        {
            "source": "השירות המטאורולוגי",
            "category": "מזג אוויר",
            "headline": "מזג האוויר בירושלים: 12°–20°; עננות חלקית",
            "context": "בירושלים צפויה עננות חלקית וקרינה גבוהה בצהריים.",
            "sourceUrl": "https://ims.gov.il/jerusalem",
        },
        {
            "source": "וואלה חדשות",
            "category": "חדשות",
            "headline": "גשם ורוחות ילוו את ערב שבועות בצפון ובמרכז",
            "context": "בערב החג צפויים גשם ורוחות בצפון ובמרכז.",
            "sourceUrl": "https://news.walla.co.il/item/3839781",
        },
    ),
    (
        "north_uav_alert_kfar_yuval_maariv_ynet_20260604",
        True,
        {
            "source": "ynet - מבזקי החדשות",
            "category": "ביטחון",
            "headline": "צה״ל זיהה מטרה חשודה בכפר יובל וסגר את אירוע ההתרעה",
            "context": "צה״ל עדכן כי באצבע הגליל זוהתה מטרה אווירית חשודה, בעוד שבגליל המערבי ההתרעה התבררה כזיהוי שווא. האירוע הסתיים ללא נפגעים.",
            "sourceUrl": "https://www.ynet.co.il/news/article/bkqxkdaege",
        },
        {
            "source": "מעריב - מבזקים",
            "category": "ביטחון",
            "headline": "חשד למטרה אווירית ליד כפר יובל; אין נפגעים",
            "context": "לאחר התרעות על חדירת כלי טיס עוין, צה״ל מסר כי ההתרעה בערב אל-עראמשה הייתה זיהוי שווא. במרחב כפר יובל זוהתה מטרה אווירית חשודה, האירוע הסתיים ולא דווח על נפגעים.",
            "sourceUrl": "https://www.maariv.co.il/breaking-news/article-1329065",
        },
    ),
    (
        "trump_iran_uranium_ground_operation_ynet_n12_visible_regression_20260605",
        True,
        {
            "source": "ynet - כל ערוץ החדשות",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "טראמפ הסתייג ממבצע קרקעי להוצאת אורניום מאיראן",
            "originalTitle": "טראמפ: שקלנו להכניס חיילים לאיראן כדי להוציא את האורניום",
            "context": "טראמפ הבהיר כי מבצע קרקעי להוצאת אורניום מאיראן נבחן אך אינו מועדף, על רקע ההסלמה סביב תוכנית הגרעין.",
            "sourceUrl": "https://www.ynet.co.il/news/article/bk00w1vywme",
        },
        {
            "source": "N12 - בעולם",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "טראמפ אמר שמבצע להוצאת האורניום מאיראן ידרוש שבועיים בשטח",
            "originalTitle": "טראמפ: מבצע להוצאת האורניום מאיראן ידרוש שבועיים בשטח",
            "context": "טראמפ אמר שמבצע אמריקני להוצאת אורניום מאיראן יחייב שהות של כשבועיים בשטח, אך הציג זאת כאפשרות מסוכנת ולא כבחירה מועדפת.",
            "sourceUrl": "https://www.mako.co.il/news-world/2026_q2/Article-29ab8b086549e91026.htm",
        },
    ),
    (
        "ireland_ben_gvir_smotrich_entry_ban_walla_israelhayom_visible_regression_20260605",
        True,
        {
            "source": "וואלה חדשות - חדשות בעולם",
            "category": "אקטואליה בעולם",
            "categoryClass": "security",
            "headline": "אירלנד חסמה את בן גביר וסמוטריץ'",
            "originalTitle": "אירלנד אוסרת על סמוטריץ' ובן גביר כניסה לשטחה: \"נקדם הרחבה לכל האיחוד האירופי\"",
            "context": "אירלנד אסרה את כניסת בן גביר וסמוטריץ' לשטחה ומקדמת הרחבת המהלך מול האיחוד האירופי.",
            "sourceUrl": "https://news.walla.co.il/item/3843438",
        },
        {
            "source": "ישראל היום - כל הכתבות",
            "category": "אקטואליה בעולם",
            "categoryClass": "security",
            "headline": "אירלנד תחסום כניסה לבן גביר וסמוטריץ'",
            "originalTitle": "אירלנד מטילה חרם אישי: השרים בן גביר וסמוטריץ' לא יורשו להיכנס",
            "context": "ממשלת אירלנד הודיעה על איסור כניסה אישי לבן גביר וסמוטריץ' כחלק מהחרפת הצעדים נגד ישראל.",
            "sourceUrl": "https://www.israelhayom.co.il/news/world-news/europe/article/20697658",
        },
    ),
    (
        "idf_officers_injured_south_lebanon_walla_ynet_visible_regression_20260605",
        True,
        {
            "source": "וואלה חדשות - מבזקים",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "שלושה קציני צה\"ל נפצעו בדרום לבנון",
            "originalTitle": "2 קצינים נפצעו באורח קשה בדרום לבנון, קצין נוסף נפצע באורח קל",
            "context": "שני קצינים נפצעו קשה וקצין נוסף נפצע קל בתקריות בדרום לבנון.",
            "sourceUrl": "https://news.walla.co.il/break/3843440",
        },
        {
            "source": "ynet - מבזקי החדשות",
            "category": "ביטחון",
            "categoryClass": "security",
            "headline": "שתי תקריות קשות לצה״ל בדרום לבנון",
            "originalTitle": "שני קצינים נפצעו קשה בתקריות שונות בדרום בלבנון, מפקד סיירת גבעתי נפצע קל",
            "context": "שני קצינים נפצעו קשה בדרום לבנון ומפקד סיירת גבעתי נפצע קל באירוע נוסף.",
            "sourceUrl": "https://www.ynet.co.il/news/article/byflr8lwfe",
        },
    ),
]


def main() -> int:
    failures = []
    for name, expected, a, b in CASES:
        got = likely_duplicate_story(a, b)
        if got != expected:
            failures.append(f"{name}: expected {expected}, got {got}")
    if failures:
        print("Semantic duplicate drill failed:")
        for failure in failures:
            print("-", failure)
        return 1

    older_detailed = {
        "source": "מקור א",
        "publishedAt": "2026-05-26T06:00:00+03:00",
        "headline": "ארה״ב תקפה בדרום איראן",
        "context": "פירוט ארוך מאוד על התקיפה, השיחות, הורמוז ובנדר עבאס " * 5,
        "takeaway": "טייקאוויי מפורט",
        "sourceUrl": "https://example.com/older",
    }
    newer_shorter = {
        "source": "מקור ב",
        "publishedAt": "2026-05-26T07:00:00+03:00",
        "headline": "ארה״ב תקפה באיראן",
        "context": "עדכון קצר אך מאוחר יותר",
        "takeaway": "",
        "sourceUrl": "https://example.com/newer",
    }
    preferred = update_feed.preferred_duplicate_item(older_detailed, newer_shorter)
    if preferred is not newer_shorter:
        print("Semantic duplicate drill failed:")
        print("- preferred_duplicate_item: expected freshest duplicate to win over older detailed card")
        return 1

    print(f"Semantic duplicate drill passed: {len(CASES)}/{len(CASES)} + freshest-preferred")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
