#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Pointa full-article editor pilot pipeline.

Safe-by-default: this script does not change feed.json or deploy anything.
It prepares editor batches from the current feed by fetching full article text,
and then validates/combines editor results into a preview feed + markdown report.

Usage:
  python scripts/pointa_editor_pipeline.py prepare --limit 24 --batch-size 8
  python scripts/pointa_editor_pipeline.py qa --run-dir tmp/editor-runs/<run-id>

The actual editorial rewrite can be done by the Pointa editor agent using the
batch_*.json files and EDITOR_PROMPT.md generated by `prepare`.
"""
from __future__ import annotations

import argparse
import glob
import html
import json
import os
import re
import sys
import time
from dataclasses import dataclass
from datetime import datetime
from html.parser import HTMLParser
from pathlib import Path
from typing import Any
from urllib.parse import urlparse
from urllib.request import Request, urlopen

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_FEED = ROOT / "feed.json"
RUNS_DIR = ROOT / "tmp" / "editor-runs"
SYNC_PROFILES_PATH = ROOT / "pointa_sync_profiles.json"

try:
    from update_feed import fetch_article_image, filter_main_feed_breaking_leaks  # type: ignore
except Exception:  # pragma: no cover
    fetch_article_image = None
    filter_main_feed_breaking_leaks = None

try:
    from pointa_quality_gate import looks_cut as quality_gate_looks_cut  # type: ignore
except Exception:  # pragma: no cover
    quality_gate_looks_cut = None

HEADERS = {
    "User-Agent": "Mozilla/5.0 (compatible; PointaEditorPipeline/0.1)",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "he-IL,he;q=0.9,en-US;q=0.7,en;q=0.5",
}

ARTICLE_FETCH_TIMEOUT = max(1, int(os.environ.get("POINTA_EDITOR_ARTICLE_FETCH_TIMEOUT", "15")))
JINA_FETCH_TIMEOUT = max(1, int(os.environ.get("POINTA_EDITOR_JINA_FETCH_TIMEOUT", "25")))
JINA_MAX_ATTEMPTS = max(0, int(os.environ.get("POINTA_EDITOR_JINA_MAX_ATTEMPTS", "2")))

CATEGORY_CLASS = {
    "ביטחון": "security",
    "פוליטיקה": "",
    "אקטואליה בעולם": "",
    "משפט": "",
    "פלילים": "",
    "כלכלה": "money",
    "צרכנות": "money",
    "טכנולוגיה": "tech",
    "רכב": "real",
    "בריאות": "real",
    "תרבות": "real",
    "רכילות": "real",
    "ספורט": "real",
    "נדל״ן": "real",
    "מזג אוויר": "real",
    "חדשות": "",
    "דעות": "",
}


def load_sync_profiles() -> dict[str, Any]:
    try:
        return json.loads(SYNC_PROFILES_PATH.read_text(encoding="utf-8"))
    except Exception:
        return {"profiles": {}, "categoryProfile": {}}


def category_profile(category: str, profiles: dict[str, Any] | None = None) -> str:
    profiles = profiles or load_sync_profiles()
    return profiles.get("categoryProfile", {}).get(category or "חדשות", "fast")

FORBIDDEN_MEDIATION = [
    "פורסם", "דיווח", "בדיווח", "לפי הדיווח", "הכתב", "המקור", "הכתבה",
    "הכתבה מציגה", "הכתבה עוסקת", "לפי הכתבה", "לפי הפרסום", "לפי המקור",
]
GENERIC_TAKEAWAYS = [
    "משנה את תמונת המצב", "השאלה היא איך", "החשיבות של", "המשמעות של",
    "הסיכון סביב", "נקודת ההשלכה המרכזית", "מחייב להבין", "מסמן מי עלול",
    "הפרט שקובע מה באמת השתנה", "הוא הפרט שקובע מה באמת השתנה", "עשוי לשנות היערכות",
]

STOPWORDS = {
    "של", "על", "את", "עם", "לא", "כי", "זה", "זו", "הוא", "היא", "הם", "הן",
    "גם", "או", "אם", "כל", "יש", "אין", "אל", "עד", "בו", "בה", "בין", "כדי",
    "לאחר", "בעקבות", "יותר", "פחות", "היום", "מחר", "אתמול", "חדש", "חדשה",
    "דיווח", "דיווחו", "פורסם", "לפי", "אחרי", "לפני",
    "סיפור", "הסיפור", "אירוע", "האירוע", "נמסר", "שבת", "חשוב", "לבדוק",
    "דרמה", "בלתי", "מוכר", "מעבר", "לצופים", "מסך", "הטלוויזיוני",
    "הביטחון", "הנחיות", "השגרה", "ולכן", "עשוי", "עשויה", "להשפיע",
    "רשמי", "רשמיות", "רשמית",
}


def clean_text(text: str) -> str:
    text = html.unescape(text or "")
    text = re.sub(r"<[^>]+>", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def compact_source_text(text: str, limit: int = 220) -> str:
    text = clean_text(text)
    if len(text) <= limit:
        return text
    cut = text[:limit].rsplit(" ", 1)[0].strip()
    return cut or text[:limit].strip()


def story_text(item: dict[str, Any]) -> str:
    current = item.get("currentCard") if isinstance(item.get("currentCard"), dict) else {}
    rescue = item.get("rescue") if isinstance(item.get("rescue"), dict) else {}
    source_row = rescue.get("sourceQueueRow") if isinstance(rescue.get("sourceQueueRow"), dict) else {}
    parts = [
        item.get("originalTitle"),
        item.get("headline"),
        item.get("description"),
        item.get("context"),
        item.get("summary"),
        item.get("articleText", "")[:900],
        current.get("headline"),
        current.get("summary"),
        source_row.get("originalTitle"),
        source_row.get("deterministicHeadline"),
        source_row.get("deterministicContext"),
    ]
    return clean_text(" ".join(str(p or "") for p in parts))


def story_match_text(item: dict[str, Any]) -> str:
    current = item.get("currentCard") if isinstance(item.get("currentCard"), dict) else {}
    rescue = item.get("rescue") if isinstance(item.get("rescue"), dict) else {}
    source_row = rescue.get("sourceQueueRow") if isinstance(rescue.get("sourceQueueRow"), dict) else {}
    parts = [
        item.get("originalTitle"),
        item.get("headline"),
        item.get("description"),
        item.get("context"),
        item.get("summary"),
        current.get("headline"),
        current.get("summary"),
        source_row.get("originalTitle"),
        source_row.get("deterministicHeadline"),
        source_row.get("deterministicContext"),
    ]
    return clean_text(" ".join(str(p or "") for p in parts))


def story_keywords(text: str) -> set[str]:
    words = re.findall(r"[A-Za-z][A-Za-z0-9'-]{2,}|[\u0590-\u05ff][\u0590-\u05ff\"׳״'-]{2,}", text or "")
    out: set[str] = set()
    for word in words:
        normalized = word.strip("\"'׳״-").lower()
        if len(normalized) < 3 or normalized in STOPWORDS:
            continue
        out.add(normalized)
    return out


def parse_dt(raw: Any) -> datetime | None:
    try:
        dt = datetime.fromisoformat(str(raw or "").replace("Z", "+00:00"))
        return dt
    except Exception:
        return None


def minutes_apart(a: datetime | None, b: datetime | None) -> float:
    if not a or not b:
        return 10_000.0
    try:
        if a.tzinfo and b.tzinfo:
            return abs((a - b).total_seconds()) / 60
        return abs((a.replace(tzinfo=None) - b.replace(tzinfo=None)).total_seconds()) / 60
    except Exception:
        return 10_000.0


def stable_background_notes(text: str, category: str, source: str) -> list[str]:
    low = text.lower()
    notes: list[str] = []
    if any(k in text for k in ["חיזבאללה", "לבנון", "דרום לבנון"]):
        notes.append("רקע יציב: בזירה הצפונית ישראל ממשיכה לדווח על אכיפה ותקיפות נקודתיות מול פעילות חיזבאללה סמוך לגבול; אין להפוך זאת לטענה על הסלמה רחבה בלי מקור נוסף.")
    if any(k in text for k in ["עזה", "חמאס", "רצועת עזה"]):
        notes.append("רקע יציב: אירועים בעזה צריכים להיות ממוסגרים סביב העובדה המדווחת בלבד; נתוני נפגעים, יעדים או אחריות אינם נכתבים בלי מקור מפורש.")
    if any(k in text for k in ["משטרה", "נעצר", "מעצר", "חשוד", "חשודים"]) or "משטרת ישראל" in source:
        notes.append("רקע יציב: בהודעות משטרה משתמשים בניסוח זהיר של חשד, חקירה ומעצרים; אין לקבוע אשמה או מניע בלי מקור מפורש.")
    if category == "אקטואליה בעולם" or any(k in low for k in ["trump", "iran", "russia", "ukraine", "china"]):
        notes.append("רקע יציב: בסיפור בינלאומי אפשר להסביר את ההקשר הגיאופוליטי רק כשהוא נובע מהפרטים שבמקורות הסמוכים.")
    return notes[:3]


def build_context_pack(item: dict[str, Any], corpus: list[dict[str, Any]], extraction: ArticleExtraction | None = None) -> dict[str, Any]:
    """Build a cautious context bundle for thin/breaking items.

    The pack is evidence for the editor, not a generated story. Related rows
    are selected by shared entities/keywords and publication proximity so a
    one-line bulletin can be enriched only when nearby material supports it.
    """
    primary_text = story_text(item)
    if extraction:
        primary_text = clean_text(" ".join([primary_text, extraction.title, extraction.description, extraction.text[:900]]))
    match_text = story_match_text(item)
    if extraction:
        match_text = clean_text(" ".join([match_text, extraction.title, extraction.description]))
    primary_keys = story_keywords(match_text)
    current_dt = parse_dt(item.get("publishedAt"))
    current_url = item.get("sourceUrl") or item.get("url") or ""
    scored: list[tuple[float, dict[str, Any], set[str]]] = []
    for other in corpus:
        other_url = other.get("sourceUrl") or other.get("url") or ""
        if other is item or (current_url and other_url == current_url):
            continue
        other_text = story_match_text(other)
        other_keys = story_keywords(other_text)
        overlap = primary_keys & other_keys
        if len(overlap) < 2:
            continue
        delta = minutes_apart(current_dt, parse_dt(other.get("publishedAt")))
        if delta > 360:
            continue
        score = len(overlap) * 3
        if delta <= 90:
            score += 4
        if (item.get("category") or "") and item.get("category") == other.get("category"):
            score += 2
        if item.get("source") != other.get("source"):
            score += 1
        scored.append((score, other, overlap))
    scored.sort(key=lambda row: (row[0], row[1].get("publishedAt") or ""), reverse=True)
    related = []
    for _score, other, overlap in scored[:5]:
        current = other.get("currentCard") if isinstance(other.get("currentCard"), dict) else {}
        related.append({
            "source": other.get("source", ""),
            "sourceUrl": other.get("sourceUrl") or other.get("url") or "",
            "publishedAt": other.get("publishedAt", ""),
            "title": compact_source_text(other.get("originalTitle") or other.get("headline") or current.get("headline") or ""),
            "summary": compact_source_text(other.get("context") or other.get("description") or current.get("summary") or ""),
            "sharedSignals": sorted(overlap)[:8],
        })
    current_card = item.get("currentCard") if isinstance(item.get("currentCard"), dict) else {}
    category = item.get("category") or current_card.get("category", "")
    background = stable_background_notes(primary_text, str(category or ""), str(item.get("source") or ""))
    return {
        "purpose": "Use only as corroborating context for thin/breaking items. Do not invent facts not present in articleText, description, relatedItems, or stableBackground.",
        "primaryFact": compact_source_text(primary_text, 360),
        "relatedItems": related,
        "stableBackground": background,
        "enrichmentLevel": "related" if related else ("background_only" if background else "none"),
    }


class ArticleParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.meta: dict[str, str] = {}
        self.paragraphs: list[str] = []
        self._in_p = False
        self._buf: list[str] = []
        self._skip_depth = 0

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        attr = {k: v or "" for k, v in attrs}
        if tag in {"script", "style", "nav", "footer", "header", "aside"}:
            self._skip_depth += 1
        if tag == "meta":
            key = (attr.get("property") or attr.get("name") or "").lower()
            value = attr.get("content") or ""
            if key and value:
                self.meta[key] = value
        if tag == "p" and self._skip_depth == 0:
            self._in_p = True
            self._buf = []

    def handle_data(self, data: str) -> None:
        if self._in_p and self._skip_depth == 0:
            self._buf.append(data)

    def handle_endtag(self, tag: str) -> None:
        if tag in {"script", "style", "nav", "footer", "header", "aside"} and self._skip_depth:
            self._skip_depth -= 1
        if tag == "p" and self._in_p:
            text = clean_text(" ".join(self._buf))
            if is_article_paragraph(text):
                self.paragraphs.append(text)
            self._in_p = False
            self._buf = []


def is_article_paragraph(text: str) -> bool:
    if len(text) < 35:
        return False
    noise = [
        "כל הזכויות", "שתפו", "עקבו אחרינו", "להצטרפות", "פרסומת", "קראו עוד",
        "לכתבות נוספות", "תגיות", "©", "Cookies", "cookie", "JavaScript",
    ]
    return not any(x.lower() in text.lower() for x in noise)


def fetch(url: str, timeout: int = 15) -> str:
    req = Request(url, headers=HEADERS)
    with urlopen(req, timeout=timeout) as response:
        charset = response.headers.get_content_charset() or "utf-8"
        return response.read().decode(charset, errors="replace")


def fetch_jina_text(url: str) -> str:
    # Keep the historical double-r.jina fallback because it has worked better
    # against several Israeli news WAFs in earlier Pointa runs.
    candidates = [
        "https://r.jina.ai/http://r.jina.ai/http://" + url,
        "https://r.jina.ai/http://" + url.replace("https://", "").replace("http://", ""),
    ]
    for reader_url in candidates[:JINA_MAX_ATTEMPTS]:
        try:
            raw = fetch(reader_url, timeout=JINA_FETCH_TIMEOUT)
        except Exception:
            continue
        lines = []
        for line in raw.splitlines():
            line = clean_text(line)
            if len(line) < 50:
                continue
            if line.startswith(("Title:", "URL Source:", "Markdown Content:")):
                continue
            if line.startswith(("![", "[")):
                continue
            lines.append(line)
        text = clean_text(" ".join(lines[:35]))
        if len(text) > 250:
            return text[:7000]
    return ""


@dataclass
class ArticleExtraction:
    text: str
    title: str = ""
    description: str = ""
    method: str = "none"


def extract_article(url: str) -> ArticleExtraction:
    if not url:
        return ArticleExtraction(text="")
    try:
        raw = fetch(url, timeout=ARTICLE_FETCH_TIMEOUT)
    except Exception:
        raw = ""
    parser = ArticleParser()
    if raw:
        try:
            parser.feed(raw)
        except Exception:
            pass
    title = clean_text(parser.meta.get("og:title") or parser.meta.get("twitter:title") or "")
    desc = clean_text(parser.meta.get("og:description") or parser.meta.get("description") or parser.meta.get("twitter:description") or "")
    text = clean_text(" ".join(parser.paragraphs[:35]))[:7000]
    if len(text) >= 350:
        return ArticleExtraction(text=text, title=title, description=desc, method="html")
    jina = fetch_jina_text(url)
    if len(jina) > len(text):
        return ArticleExtraction(text=jina, title=title, description=desc, method="jina")
    return ArticleExtraction(text=text, title=title, description=desc, method="html-short" if text else "none")


def load_feed(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as f:
        return json.load(f)


def parse_dt_for_sort(raw: Any) -> datetime:
    try:
        return datetime.fromisoformat(str(raw or "").replace("Z", "+00:00"))
    except Exception:
        return datetime.min


def select_items(feed: dict[str, Any], limit: int, max_per_source: int, max_per_category: int, sync_profile: str = "all") -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    by_source: dict[str, int] = {}
    by_cat: dict[str, int] = {}
    seen_urls: set[str] = set()
    profiles = load_sync_profiles()
    for item in feed.get("items", []):
        url = item.get("sourceUrl") or ""
        if not url or url in seen_urls:
            continue
        source = item.get("source") or urlparse(url).netloc
        category = item.get("category") or "חדשות"
        if sync_profile != "all" and category_profile(category, profiles) != sync_profile:
            continue
        if by_source.get(source, 0) >= max_per_source:
            continue
        if by_cat.get(category, 0) >= max_per_category:
            continue
        out.append(item)
        seen_urls.add(url)
        by_source[source] = by_source.get(source, 0) + 1
        by_cat[category] = by_cat.get(category, 0) + 1
        if len(out) >= limit:
            break
    return out


def make_editor_input(items: list[dict[str, Any]]) -> list[dict[str, Any]]:
    out = []
    for index, item in enumerate(items):
        url = item.get("sourceUrl") or ""
        extraction = extract_article(url)
        original_title = item.get("originalTitle") or extraction.title or item.get("headline") or ""
        description = extraction.description or item.get("context") or ""
        out.append({
            "index": index,
            "source": item.get("source", ""),
            "sourceUrl": url,
            "originalTitle": original_title,
            "description": description,
            "articleText": extraction.text,
            "articleTextChars": len(extraction.text),
            "articleTextMethod": extraction.method,
            "contextPack": build_context_pack(item, items, extraction),
            "publishedAt": item.get("publishedAt", ""),
            "language": "he",
            "currentCard": {
                "category": item.get("category", ""),
                "categoryClass": item.get("categoryClass", ""),
                "headline": item.get("headline", ""),
                "summary": item.get("context", ""),
                "takeaway": item.get("takeaway", ""),
            },
            "feedItem": item,
        })
    return out


def write_prompt(run_dir: Path, batch_files: list[Path]) -> None:
    batches = ", ".join(p.name for p in batch_files)
    prompt = f"""# Pointa editor pilot run

Process each `batch_*.json` file in this directory: {batches}

For every item:
1. Use `articleText` as the primary source when `articleTextChars` is sufficient.
2. For one-line bulletins, use `contextPack.relatedItems` and `contextPack.stableBackground` only as corroborating context. Do not invent names, casualties, motives, targets, or consequences that are not supported there.
3. Do not summarize the RSS. Identify the real story, important facts, and bottom line.
4. Return `reject` when `articleText` is thin and `contextPack` does not contain enough related evidence for a specific Pointa takeaway.
5. Keep Hebrew output concise and follow the Pointa editor contract.
6. Category boundary: `אקטואליה בעולם` is only for global stories with no Israel/Middle-East angle. If the item is about Israel, Gaza, Iran, the Abraham Accords, normalization with Israel, or Middle-East diplomacy/security, use the normal domains (`ביטחון`, `פוליטיקה`, or `חדשות`) even when the source is foreign.

Write one result file per batch, named `batch_N_results.json`.
Each result object must include:

```json
{{
  "index": 0,
  "status": "pass|reject",
  "category": "...",
  "categoryClass": "security|money|tech|real|",
  "headline": "...",
  "summary": "...",
  "takeaway": "...",
  "rejectReason": "",
  "qualityNotes": ["..."],
  "currentProblems": ["..."],
  "changedFields": {{"headline": true, "summary": true, "takeaway": true, "category": false}}
}}
```
"""
    (run_dir / "EDITOR_PROMPT.md").write_text(prompt, encoding="utf-8")


def command_prepare(args: argparse.Namespace) -> int:
    feed = load_feed(Path(args.feed))
    selected = select_items(feed, args.limit, args.max_per_source, args.max_per_category, args.sync_profile)
    run_id = args.run_id or datetime.now().strftime("%Y%m%d-%H%M%S")
    run_dir = RUNS_DIR / run_id
    run_dir.mkdir(parents=True, exist_ok=True)
    editor_input = make_editor_input(selected)
    (run_dir / "editor_input.json").write_text(json.dumps(editor_input, ensure_ascii=False, indent=2), encoding="utf-8")
    batch_files = []
    for batch_index, start in enumerate(range(0, len(editor_input), args.batch_size), start=1):
        batch = editor_input[start:start + args.batch_size]
        path = run_dir / f"batch_{batch_index}.json"
        path.write_text(json.dumps(batch, ensure_ascii=False, indent=2), encoding="utf-8")
        batch_files.append(path)
    write_prompt(run_dir, batch_files)
    metadata = {
        "runId": run_id,
        "createdAt": datetime.now().isoformat(timespec="seconds"),
        "feed": str(Path(args.feed).resolve()),
        "syncProfile": args.sync_profile,
        "items": len(editor_input),
        "usableArticleText": sum(1 for x in editor_input if x.get("articleTextChars", 0) >= args.min_article_chars),
        "batchSize": args.batch_size,
        "batches": [p.name for p in batch_files],
    }
    (run_dir / "run.json").write_text(json.dumps(metadata, ensure_ascii=False, indent=2), encoding="utf-8")
    print(run_dir)
    print(json.dumps(metadata, ensure_ascii=False, indent=2))
    return 0


def too_close(a: str, b: str) -> bool:
    a_words = set(re.findall(r"[\w\u0590-\u05ff]+", (a or "").lower()))
    b_words = set(re.findall(r"[\w\u0590-\u05ff]+", (b or "").lower()))
    if not a_words or not b_words:
        return False
    return len(a_words & b_words) / max(1, min(len(a_words), len(b_words))) >= 0.75


def validate_result(result: dict[str, Any], source: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    status = result.get("status")
    if status not in {"pass", "reject"}:
        errors.append("status must be pass/reject")
    if status == "reject":
        if not result.get("rejectReason"):
            errors.append("reject missing rejectReason")
        return errors
    headline = clean_text(result.get("headline", ""))
    summary = clean_text(result.get("summary", ""))
    takeaway = clean_text(result.get("takeaway", ""))
    category = result.get("category", "")
    if not headline:
        errors.append("missing headline")
    if len(headline) > 75:
        errors.append("headline over 75 chars")
    if "..." in headline or "…" in headline:
        errors.append("headline has ellipsis")
    if callable(quality_gate_looks_cut) and quality_gate_looks_cut(headline):
        errors.append("headline appears mechanically cut")
    if too_close(headline, source.get("originalTitle", "")):
        errors.append("headline too close to source title")
    if not summary:
        errors.append("missing summary")
    if any(x in summary for x in FORBIDDEN_MEDIATION):
        errors.append("summary contains mediation wording")
    if headline and summary and summary.startswith(headline):
        errors.append("headline is just the opening fragment of the summary")
    sentence_text = re.sub(r"(?<=\d)[.](?=\d)", "", summary)
    sentence_count = len([s for s in re.split(r"[.!?؟]+", sentence_text) if s.strip()])
    if sentence_count > 2:
        errors.append("summary has more than 2 sentences")
    if not takeaway:
        errors.append("missing takeaway")
    if any(x in takeaway for x in GENERIC_TAKEAWAYS):
        errors.append("takeaway has generic banned pattern")
    if category not in CATEGORY_CLASS:
        errors.append("unknown category")
    me_or_israel_terms = ["ישראל", "israel", "הסכמי אברהם", "abraham accords", "middle east", "mideast", "מזרח תיכון", "עזה", "gaza", "חמאס", "חיזבאללה", "לבנון", "איראן", "iran", "הורמוז", "סעודיה", "קטאר", "מצרים", "ירדן", "טורקיה", "פלסטיני"]
    world_only_terms = ["קובה", "cuba", "פוקושימה", "fukushima"]
    strong_local_terms = ["ישראל", "israel", "הסכמי אברהם", "abraham accords", "middle east", "mideast", "עזה", "gaza"]
    content_low = " ".join([headline, summary, takeaway, source.get("originalTitle", "")]).lower()
    source_low = str(source.get("source", "")).lower()
    is_me_or_israel = (
        any(x.lower() in content_low for x in me_or_israel_terms)
        and (not any(x.lower() in content_low for x in world_only_terms) or any(x.lower() in content_low for x in strong_local_terms))
    ) or any(x in source_low for x in ["middle east", "mideast", "מזרח תיכון"])
    if category == "אקטואליה בעולם" and is_me_or_israel:
        errors.append("category_world_boundary")
    expected_class = CATEGORY_CLASS.get(category, "")
    if result.get("categoryClass", "") != expected_class:
        errors.append(f"categoryClass should be {expected_class!r}")
    return errors


def read_results(run_dir: Path) -> list[dict[str, Any]]:
    results: list[dict[str, Any]] = []
    for path in sorted(run_dir.glob("batch_*_results.json")):
        with path.open(encoding="utf-8") as f:
            data = json.load(f)
        if not isinstance(data, list):
            raise ValueError(f"{path} must contain a JSON array")
        for result in data:
            # categoryClass is derived UI metadata. Let the editor decide the
            # category, but normalize this field before QA/apply so minor class
            # mismatches do not block otherwise good editorial work.
            if result.get("status") == "pass" and result.get("category") in CATEGORY_CLASS:
                result["categoryClass"] = CATEGORY_CLASS[result["category"]]
        results.extend(data)
    return results


def is_gossip_source(source: str) -> bool:
    return any(x in source for x in ["סלבס", "TMI", "Pplus", "פנאי פלוס", "פפראצי", "פפארצי", "רכילות", "Celebs"])


def editor_source_item(row: dict[str, Any]) -> dict[str, Any]:
    if isinstance(row.get("feedItem"), dict):
        return dict(row["feedItem"])
    return {
        "source": row.get("source", ""),
        "sourceGroup": row.get("sourceGroup", ""),
        "sourceUrl": row.get("sourceUrl", ""),
        "originalTitle": row.get("originalTitle", ""),
        "publishedAt": row.get("publishedAt", ""),
        "category": row.get("suggestedCard", {}).get("category", row.get("currentCard", {}).get("category", "")),
        "categoryClass": row.get("suggestedCard", {}).get("categoryClass", row.get("currentCard", {}).get("categoryClass", "")),
        "headline": row.get("currentCard", {}).get("headline", ""),
        "context": row.get("currentCard", {}).get("summary", row.get("description", "")),
        "takeaway": row.get("currentCard", {}).get("takeaway", ""),
        "imageUrl": row.get("imageUrl") or row.get("image") or row.get("feedItem", {}).get("imageUrl") or "",
        "rescueSource": row.get("rescue", {}).get("source", ""),
    }


def build_preview_feed(feed: dict[str, Any], editor_input: list[dict[str, Any]], results: list[dict[str, Any]]) -> dict[str, Any]:
    by_index = {int(r["index"]): r for r in results if "index" in r}
    input_by_index = {int(x["index"]): x for x in editor_input}
    rejects = {editor_source_item(input_by_index[i]).get("sourceUrl") for i, r in by_index.items() if r.get("status") == "reject" and i in input_by_index}
    rewritten: dict[str, dict[str, Any]] = {}
    ordered_new: list[dict[str, Any]] = []
    feed_urls = {item.get("sourceUrl") for item in feed.get("items", [])}
    for i, r in sorted(by_index.items()):
        if r.get("status") != "pass" or i not in input_by_index:
            continue
        item = editor_source_item(input_by_index[i])
        item["category"] = r.get("category", item.get("category", ""))
        item["categoryClass"] = r.get("categoryClass", item.get("categoryClass", ""))
        if is_gossip_source(str(item.get("source") or "")):
            item["category"] = "רכילות"
            item["categoryClass"] = "real"
        item["headline"] = r.get("headline", item.get("headline", ""))
        item["context"] = r.get("summary", item.get("context", ""))
        item["takeaway"] = r.get("takeaway", item.get("takeaway", ""))
        if not str(item.get("imageUrl") or "").strip() and fetch_article_image:
            image = fetch_article_image(str(item.get("sourceUrl") or ""))
            if image:
                item["imageUrl"] = image
        if os.environ.get("POENTA_IMAGE_BANK_ENABLED", "1") != "0" and apply_poenta_image_bank_to_item:
            item, _image_bank_info = apply_poenta_image_bank_to_item(item)
        item["editorStatus"] = "pass"
        item["editorAddedAt"] = datetime.now().isoformat(timespec="seconds")
        url = item.get("sourceUrl")
        rewritten[url] = item
        if url and url not in feed_urls:
            ordered_new.append(item)
    preview = dict(feed)
    preview_items = []
    seen_urls: set[str] = set()
    for item in ordered_new:
        url = item.get("sourceUrl")
        if not url or url in seen_urls or url in rejects:
            continue
        preview_items.append(item)
        seen_urls.add(url)
    for item in feed.get("items", []):
        url = item.get("sourceUrl")
        if url in rejects or url in seen_urls:
            continue
        preview_items.append(rewritten.get(url, item))
        if url:
            seen_urls.add(url)
    preview_items.sort(key=lambda item: parse_dt_for_sort(item.get("publishedAt")), reverse=True)
    for item in preview_items:
        if isinstance(item, dict):
            item["categoryClass"] = CATEGORY_CLASS.get(str(item.get("category") or ""), "")
            item.pop("takeaway", None)
    preview["items"] = preview_items

    # Source-filter dashboards and personal source views are driven by
    # sourceActivity, not only by the visible item list.  When the editor rescues
    # a source whose deterministic card was dropped, record that fresh activity
    # in the same preview/apply artifact so a selected source no longer appears
    # stale or empty after publication.
    activity_by_key: dict[tuple[str, str], dict[str, Any]] = {}
    for row in preview.get("sourceActivity", []) or []:
        if not isinstance(row, dict):
            continue
        key = (str(row.get("source") or ""), str(row.get("subSource") or ""))
        if key[0]:
            activity_by_key[key] = dict(row)
    for item in ordered_new:
        source = str(item.get("sourceGroup") or item.get("sourceLogo") or item.get("source") or "")
        sub_source = str(item.get("source") or source)
        if not source:
            continue
        row = {
            "source": source,
            "subSource": sub_source,
            "category": item.get("category") or "חדשות",
            "publishedAt": item.get("publishedAt") or "",
            "title": item.get("headline") or item.get("originalTitle") or "",
            "url": item.get("sourceUrl") or "",
        }
        key = (source, sub_source)
        old = activity_by_key.get(key)
        if not old or (row.get("publishedAt") or "") >= (old.get("publishedAt") or ""):
            activity_by_key[key] = row
    if activity_by_key:
        preview["sourceActivity"] = sorted(activity_by_key.values(), key=lambda x: (x.get("publishedAt") or "", x.get("source") or ""), reverse=True)

    preview["updatedAt"] = datetime.now().astimezone().isoformat(timespec="seconds")
    preview["editorPreview"] = {
        "createdAt": datetime.now().isoformat(timespec="seconds"),
        "rewritten": len(rewritten),
        "added": len(ordered_new),
        "rejected": len(rejects),
        "note": "Preview only; feed.json was not changed.",
    }
    return preview


def write_report(run_dir: Path, editor_input: list[dict[str, Any]], results: list[dict[str, Any]]) -> tuple[int, int]:
    by_input = {int(x["index"]): x for x in editor_input}
    errors_by_index: dict[int, list[str]] = {}
    for result in results:
        idx = int(result.get("index", -1))
        source = by_input.get(idx, {})
        errors = validate_result(result, source)
        if errors:
            errors_by_index[idx] = errors
    passes = sum(1 for r in results if r.get("status") == "pass")
    rejects = sum(1 for r in results if r.get("status") == "reject")
    lines = [
        "# Pointa Editor Pipeline QA Report",
        "",
        f"- Items prepared: {len(editor_input)}",
        f"- Results received: {len(results)}",
        f"- Pass: {passes}",
        f"- Reject: {rejects}",
        f"- QA failures: {len(errors_by_index)}",
        f"- Usable article text: {sum(1 for x in editor_input if x.get('articleTextChars', 0) >= 350)}/{len(editor_input)}",
        "",
    ]
    for result in sorted(results, key=lambda r: int(r.get("index", 0))):
        idx = int(result.get("index", -1))
        src = by_input.get(idx, {})
        cur = src.get("currentCard", {})
        lines += [
            f"## {idx}. {src.get('source', '')} — {src.get('originalTitle', '')}",
            f"URL: {src.get('sourceUrl', '')}",
            f"Article text: {src.get('articleTextChars', 0)} chars via {src.get('articleTextMethod', '')}",
            "",
            "**Current**",
            f"- Category: {cur.get('category', '')}",
            f"- Headline: {cur.get('headline', '')}",
            f"- Summary: {cur.get('summary', '')}",
            f"- Takeaway: {cur.get('takeaway', '')}",
            "",
            "**Editor**",
            f"- Status: {result.get('status', '')}",
        ]
        if result.get("status") == "reject":
            lines.append(f"- Reject reason: {result.get('rejectReason', '')}")
        else:
            lines += [
                f"- Category: {result.get('category', '')}",
                f"- Headline: {result.get('headline', '')}",
                f"- Summary: {result.get('summary', '')}",
                f"- Takeaway: {result.get('takeaway', '')}",
            ]
        if result.get("currentProblems"):
            lines.append(f"- Current problems: {'; '.join(result.get('currentProblems') or [])}")
        if result.get("qualityNotes"):
            lines.append(f"- Quality notes: {'; '.join(result.get('qualityNotes') or [])}")
        if errors_by_index.get(idx):
            lines.append(f"- QA errors: {'; '.join(errors_by_index[idx])}")
        lines.append("")
    (run_dir / "qa_report.md").write_text("\n".join(lines), encoding="utf-8")
    return len(errors_by_index), rejects


def auto_reject_failed_results(run_dir: Path, editor_input: list[dict[str, Any]]) -> int:
    """Turn invalid pass results into rejects so one bad card does not stale a whole run."""
    by_input = {int(x["index"]): x for x in editor_input}
    changed = 0
    for path in sorted(run_dir.glob("batch_*_results.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        file_changed = False
        for result in data:
            idx = int(result.get("index", -1))
            if result.get("status") != "pass":
                continue
            errors = validate_result(result, by_input.get(idx, {}))
            if not errors:
                continue
            result["status"] = "reject"
            result["rejectReason"] = "QA auto-rejected: " + "; ".join(errors)
            result["headline"] = ""
            result["summary"] = ""
            result["takeaway"] = ""
            result.setdefault("qualityNotes", [])
            result.setdefault("currentProblems", [])
            changed += 1
            file_changed = True
        if file_changed:
            path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return changed


def command_qa(args: argparse.Namespace) -> int:
    run_dir = Path(args.run_dir)
    feed = load_feed(Path(args.feed))
    editor_input = json.loads((run_dir / "editor_input.json").read_text(encoding="utf-8"))
    results = read_results(run_dir)
    if not results:
        print(f"No batch_*_results.json files found in {run_dir}", file=sys.stderr)
        return 2
    if args.auto_reject_failed:
        changed = auto_reject_failed_results(run_dir, editor_input)
        if changed:
            print(f"Auto-rejected {changed} invalid editor result(s)", file=sys.stderr)
            results = read_results(run_dir)
    errors, rejects = write_report(run_dir, editor_input, results)
    preview = build_preview_feed(feed, editor_input, results)
    if callable(filter_main_feed_breaking_leaks):
        preview["items"] = filter_main_feed_breaking_leaks(
            list(preview.get("items") or []),
            "editor_preview_main_feed_no_breaking_guard",
        )
    (run_dir / "feed_editor_preview.json").write_text(json.dumps(preview, ensure_ascii=False, indent=2), encoding="utf-8")
    summary = {
        "runDir": str(run_dir),
        "itemsPrepared": len(editor_input),
        "results": len(results),
        "pass": sum(1 for r in results if r.get("status") == "pass"),
        "reject": rejects,
        "qaFailures": errors,
        "report": str(run_dir / "qa_report.md"),
        "previewFeed": str(run_dir / "feed_editor_preview.json"),
    }
    (run_dir / "qa_summary.json").write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(summary, ensure_ascii=False, indent=2))
    return 1 if errors else 0


def command_apply(args: argparse.Namespace) -> int:
    run_dir = Path(args.run_dir)
    summary_path = run_dir / "qa_summary.json"
    preview_path = run_dir / "feed_editor_preview.json"
    if not summary_path.exists() or not preview_path.exists():
        print("Run editor:qa before apply", file=sys.stderr)
        return 2
    summary = json.loads(summary_path.read_text(encoding="utf-8"))
    if int(summary.get("qaFailures", 1)) != 0:
        print(f"Refusing to apply editor preview: qaFailures={summary.get('qaFailures')}", file=sys.stderr)
        return 3
    feed = json.loads(preview_path.read_text(encoding="utf-8"))
    if callable(filter_main_feed_breaking_leaks):
        feed["items"] = filter_main_feed_breaking_leaks(
            list(feed.get("items") or []),
            "editor_apply_main_feed_no_breaking_guard",
        )
    for item in feed.get("items", []) or []:
        if isinstance(item, dict):
            item["categoryClass"] = CATEGORY_CLASS.get(str(item.get("category") or ""), "")
            item.pop("takeaway", None)
    # Keep a small audit marker but avoid preview-only wording in the live file.
    feed["editorRun"] = {
        "runDir": str(run_dir),
        "appliedAt": datetime.now().isoformat(timespec="seconds"),
        "rewritten": int(summary.get("pass", 0)),
        "rejected": int(summary.get("reject", 0)),
        "qaFailures": 0,
    }
    feed.pop("editorPreview", None)
    FEED_PATH = Path(args.feed)
    FEED_PATH.write_text(json.dumps(feed, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    state = {
        "lastRun": feed.get("updatedAt") or datetime.now().isoformat(timespec="seconds"),
        "count": len(feed.get("items", [])),
        "editorRun": str(run_dir),
        "editorPass": int(summary.get("pass", 0)),
        "editorReject": int(summary.get("reject", 0)),
    }
    (ROOT / ".poanta-state.json").write_text(json.dumps(state, ensure_ascii=False), encoding="utf-8")
    print(json.dumps({"applied": str(FEED_PATH), **state}, ensure_ascii=False, indent=2))
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("prepare", help="Prepare full-article editor batches from feed.json")
    p.add_argument("--feed", default=str(DEFAULT_FEED))
    p.add_argument("--limit", type=int, default=24)
    p.add_argument("--batch-size", type=int, default=8)
    p.add_argument("--max-per-source", type=int, default=3)
    p.add_argument("--max-per-category", type=int, default=4)
    p.add_argument("--sync-profile", choices=["all", "fast", "medium", "slow"], default="all")
    p.add_argument("--min-article-chars", type=int, default=350)
    p.add_argument("--run-id", default="")
    p.set_defaults(func=command_prepare)

    q = sub.add_parser("qa", help="Validate editor result batches and build preview feed")
    q.add_argument("--run-dir", required=True)
    q.add_argument("--feed", default=str(DEFAULT_FEED))
    q.add_argument("--auto-reject-failed", action="store_true", help="Convert invalid pass results to rejects before building preview")
    q.set_defaults(func=command_qa)

    a = sub.add_parser("apply", help="Apply a QA-passing editor preview to feed.json")
    a.add_argument("--run-dir", required=True)
    a.add_argument("--feed", default=str(DEFAULT_FEED))
    a.set_defaults(func=command_apply)
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
